/**
 * Conformance cases for the Markdown to Word parser: [id, Markdown, the HTML
 * CommonMark 0.31.2 and GFM 0.29 give for it]. conformance.test.ts renders
 * the parser's tree as HTML and compares.
 *
 * Written for the review of the parser (pull request #322). Many inputs and
 * expected outputs are adapted from examples in the CommonMark Spec and the
 * GitHub Flavored Markdown Spec, by John MacFarlane and contributors,
 * licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/):
 * https://spec.commonmark.org/0.31.2/ and https://github.github.com/gfm/.
 * Changes: the expected HTML is rewritten for this test's renderer, and some
 * examples are shortened or combined. This file as a whole is licensed under
 * CC BY-SA 4.0. It is test data only: nothing in the app imports it, and it
 * is not part of the build or the image.
 */
export const CONFORMANCE_CASES: [id: string, markdown: string, html: string][] = [
    // ── Tabs ──
    ["tab-1 tab inside indented code kept", "\tfoo\tbaz\t\tbim", "<pre><code>foo\tbaz\t\tbim\n</code></pre>"],
    ["tab-4", "  - foo\n\n\tbar", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>"],
    ["tab-5", "- foo\n\n\t\tbar", "<ul>\n<li>\n<p>foo</p>\n<pre><code>  bar\n</code></pre>\n</li>\n</ul>"],
    ["tab in fenced code kept", "```make\nall:\n\tgcc -o a a.c\n```", "<pre><code class=\"language-make\">all:\n\tgcc -o a a.c\n</code></pre>"],

    // ── Thematic breaks ──
    ["hr-1", "***\n---\n___", "<hr />\n<hr />\n<hr />"],
    ["hr-2", "+++", "<p>+++</p>"],
    ["hr-4", "--\n**\n__", "<p>--\n**\n__</p>"],
    ["hr-6", "Foo\n    ***", "<p>Foo\n***</p>"],
    ["hr-spaces", " - - -", "<hr />"],
    ["hr-mixed", " **  * ** * ** * **", "<hr />"],
    ["hr-not", "_ _ _ _ a\n\na------\n\n---a---", "<p>_ _ _ _ a</p>\n<p>a------</p>\n<p>---a---</p>"],
    ["hr-emph", " *-*", "<p><em>-</em></p>"],
    ["hr-list", "- foo\n***\n- bar", "<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>"],
    ["hr-para", "Foo\n***\nbar", "<p>Foo</p>\n<hr />\n<p>bar</p>"],
    ["hr-in-list", "- Foo\n- * * *", "<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>"],

    // ── ATX headings ──
    ["atx-7", "####### foo", "<p>####### foo</p>"],
    ["atx-nospace", "#5 bolt\n\n#hashtag", "<p>#5 bolt</p>\n<p>#hashtag</p>"],
    ["atx-escaped", "\\## foo", "<p>## foo</p>"],
    ["atx-inline", "# foo *bar* \\*baz\\*", "<h1>foo <em>bar</em> *baz*</h1>"],
    ["atx-ws", "#                  foo                     ", "<h1>foo</h1>"],
    ["atx-closing", "## foo ##\n  ###   bar    ###", "<h2>foo</h2>\n<h3>bar</h3>"],
    ["atx-closing-long", "# foo ##################################\n##### foo ##", "<h1>foo</h1>\n<h5>foo</h5>"],
    ["atx-closing-trail", "### foo ###     ", "<h3>foo</h3>"],
    ["atx-not-closing", "### foo ### b", "<h3>foo ### b</h3>"],
    ["atx-hash-attached", "# foo#", "<h1>foo#</h1>"],
    ["atx-escaped-closing", "### foo \\###\n## foo #\\##\n# foo \\#", "<h3>foo ###</h3>\n<h2>foo ###</h2>\n<h1>foo #</h1>"],
    ["atx-interrupt", "Foo bar\n# baz\nBar foo", "<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>"],
    ["atx-empty", "## \n#\n### ###", "<h2></h2>\n<h1></h1>\n<h3></h3>"],
    ["atx-indented4", "foo\n    # bar", "<p>foo\n# bar</p>"],

    // ── Setext headings ──
    ["setext-1", "Foo *bar*\n=========\n\nFoo *bar*\n---------", "<h1>Foo <em>bar</em></h1>\n<h2>Foo <em>bar</em></h2>"],
    ["setext-multiline", "Foo *bar\nbaz*\n====", "<h1>Foo <em>bar\nbaz</em></h1>"],
    ["setext-indent", "   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===", "<h2>Foo</h2>\n<h2>Foo</h2>\n<h1>Foo</h1>"],
    ["setext-code", "    Foo\n    ---\n\n    Foo\n---", "<pre><code>Foo\n---\n\nFoo\n</code></pre>\n<hr />"],
    ["setext-underline-indent", "Foo\n   ----      ", "<h2>Foo</h2>"],
    ["setext-4spaces", "Foo\n    ---", "<p>Foo\n---</p>"],
    ["setext-spaces-inside", "Foo\n= =\n\nFoo\n--- -", "<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />"],
    ["setext-hardbreak", "Foo  \n-----", "<h2>Foo</h2>"],
    ["setext-backslash", "Foo\\\n----", "<h2>Foo\\</h2>"],
    ["setext-bq", "> Foo\n---", "<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />"],
    ["setext-bq-lazy", "> foo\nbar\n===", "<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>"],
    ["setext-list", "- Foo\n---", "<ul>\n<li>Foo</li>\n</ul>\n<hr />"],
    ["setext-twolines", "Foo\nBar\n---", "<h2>Foo\nBar</h2>"],
    ["setext-seq", "---\nFoo\n---\nBar\n---\nBaz", "<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>"],
    ["setext-empty", "\n====", "<p>====</p>"],
    ["setext-escaped-gt", "\\> foo\n------", "<h2>&gt; foo</h2>"],
    ["setext-after-blank", "Foo\n\nbar\n---\nbaz", "<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>"],
    ["setext-escaped-dash", "Foo\nbar\n\\---\nbaz", "<p>Foo\nbar\n---\nbaz</p>"],

    // ── Indented code ──
    ["icode-chunks", "    chunk1\n\n    chunk2\n  \n \n \n    chunk3", "<pre><code>chunk1\n\nchunk2\n\n\n\nchunk3\n</code></pre>"],
    ["icode-blankline-spaces", "    chunk1\n      \n      chunk2", "<pre><code>chunk1\n  \n  chunk2\n</code></pre>"],
    ["icode-not-interrupt", "Foo\n    bar", "<p>Foo\nbar</p>"],
    ["icode-then-para", "    foo\nbar", "<pre><code>foo\n</code></pre>\n<p>bar</p>"],
    ["icode-mixed", "# Heading\n    foo\nHeading\n------\n    foo\n----", "<h1>Heading</h1>\n<pre><code>foo\n</code></pre>\n<h2>Heading</h2>\n<pre><code>foo\n</code></pre>\n<hr />"],
    ["icode-trailing", "    foo  ", "<pre><code>foo  \n</code></pre>"],

    // ── Fenced code ──
    ["fence-basic", "```\n<\n >\n```", "<pre><code>&lt;\n &gt;\n</code></pre>"],
    ["fence-tilde", "~~~\n<\n >\n~~~", "<pre><code>&lt;\n &gt;\n</code></pre>"],
    ["fence-two-backticks", "``\nfoo\n``", "<p><code>foo</code></p>"],
    ["fence-other-char", "```\naaa\n~~~\n```", "<pre><code>aaa\n~~~\n</code></pre>"],
    ["fence-other-char2", "~~~\naaa\n```\n~~~", "<pre><code>aaa\n```\n</code></pre>"],
    ["fence-shorter", "````\naaa\n```\n``````", "<pre><code>aaa\n```\n</code></pre>"],
    ["fence-unclosed", "```", "<pre><code></code></pre>"],
    ["fence-unclosed2", "`````\n\n```\naaa", "<pre><code>\n```\naaa\n</code></pre>"],
    ["fence-in-bq", "> ```\n> aaa\n\nbbb", "<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>"],
    ["fence-blank", "```\n\n  \n```", "<pre><code>\n  \n</code></pre>"],
    ["fence-indent1", " ```\n aaa\naaa\n```", "<pre><code>aaa\naaa\n</code></pre>"],
    ["fence-indent2", "  ```\naaa\n  aaa\naaa\n  ```", "<pre><code>aaa\naaa\naaa\n</code></pre>"],
    ["fence-indent3", "   ```\n   aaa\n    aaa\n  aaa\n   ```", "<pre><code>aaa\n aaa\naaa\n</code></pre>"],
    ["fence-indent4", "    ```\n    aaa\n    ```", "<pre><code>```\naaa\n```\n</code></pre>"],
    ["fence-close-indent", "```\naaa\n  ```", "<pre><code>aaa\n</code></pre>"],
    ["fence-close-indent4", "```\naaa\n    ```", "<pre><code>aaa\n    ```\n</code></pre>"],
    ["fence-inline", "``` ```\naaa", "<p><code> </code>\naaa</p>"],
    ["fence-close-spaces", "~~~~~~\naaa\n~~~ ~~", "<pre><code>aaa\n~~~ ~~\n</code></pre>"],
    ["fence-interrupt", "foo\n```\nbar\n```\nbaz", "<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>"],
    ["fence-info", "~~~~    ruby startline=3 $%@#$\ndef foo(x)\n  return 3\nend\n~~~~~~~", "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>"],
    ["fence-info-semicolon", "````;\n````", "<pre><code class=\"language-;\"></code></pre>"],
    ["fence-backtick-info", "``` aa ```\nfoo", "<p><code>aa</code>\nfoo</p>"],
    ["fence-tilde-info-backticks", "~~~ aa ``` ~~~\nfoo\n~~~", "<pre><code class=\"language-aa\">foo\n</code></pre>"],
    ["fence-close-with-info", "```\n``` aaa\n```", "<pre><code>``` aaa\n</code></pre>"],

    // ── Block quotes ──
    ["bq-basic", "> # Foo\n> bar\n> baz", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>"],
    ["bq-nospace", "># Foo\n>bar\n> baz", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>"],
    ["bq-lazy", "> bar\nbaz\n> foo", "<blockquote>\n<p>bar\nbaz\nfoo</p>\n</blockquote>"],
    ["bq-list-then-list", "> - foo\n- bar", "<blockquote>\n<ul>\n<li>foo</li>\n</ul>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>"],
    ["bq-code-lazy", ">     foo\n    bar", "<blockquote>\n<pre><code>foo\n</code></pre>\n</blockquote>\n<pre><code>bar\n</code></pre>"],
    ["bq-fence-lazy", "> ```\nfoo\n```", "<blockquote>\n<pre><code></code></pre>\n</blockquote>\n<p>foo</p>\n<pre><code></code></pre>"],
    ["bq-lazy-dash", "> foo\n    - bar", "<blockquote>\n<p>foo\n- bar</p>\n</blockquote>"],
    ["bq-empty", ">", "<blockquote>\n</blockquote>"],
    ["bq-two", "> foo\n\n> bar", "<blockquote>\n<p>foo</p>\n</blockquote>\n<blockquote>\n<p>bar</p>\n</blockquote>"],
    ["bq-two-paras", "> foo\n>\n> bar", "<blockquote>\n<p>foo</p>\n<p>bar</p>\n</blockquote>"],
    ["bq-interrupt", "foo\n> bar", "<p>foo</p>\n<blockquote>\n<p>bar</p>\n</blockquote>"],
    ["bq-hr", "> aaa\n***\n> bbb", "<blockquote>\n<p>aaa</p>\n</blockquote>\n<hr />\n<blockquote>\n<p>bbb</p>\n</blockquote>"],
    ["bq-nested-lazy", "> > > foo\nbar", "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n</blockquote>\n</blockquote>"],
    ["bq-nested-lazy2", ">>> foo\n> bar\n>>baz", "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar\nbaz</p>\n</blockquote>\n</blockquote>\n</blockquote>"],
    ["bq-code-vs-text", ">     code\n\n>    not code", "<blockquote>\n<pre><code>code\n</code></pre>\n</blockquote>\n<blockquote>\n<p>not code</p>\n</blockquote>"],
    ["bq-with-list-and-code", "> Steps:\n>\n> 1. Install:\n>    ```bash\n>    pip install x\n>    ```\n> 2. Run it.\n>    - with `--fast`\n>    - or not", "<blockquote>\n<p>Steps:</p>\n<ol>\n<li>Install:\n<pre><code class=\"language-bash\">pip install x\n</code></pre>\n</li>\n<li>Run it.\n<ul>\n<li>with <code>--fast</code></li>\n<li>or not</li>\n</ul>\n</li>\n</ol>\n</blockquote>"],

    // ── List items ──
    ["li-1", "1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>"],
    ["li-not-indented-enough", "- one\n\n two", "<ul>\n<li>one</li>\n</ul>\n<p>two</p>"],
    ["li-indented", "- one\n\n  two", "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>"],
    ["li-wide-marker", " -    one\n\n     two", "<ul>\n<li>one</li>\n</ul>\n<pre><code> two\n</code></pre>"],
    ["li-wide-marker2", " -    one\n\n      two", "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>"],
    ["li-in-bq", "   > > 1.  one\n>>\n>>     two", "<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>"],
    ["li-in-bq2", ">>- one\n>>\n  >  > two", "<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>"],
    ["li-no-space", "-one\n\n2.two", "<p>-one</p>\n<p>2.two</p>"],
    ["li-blank-lines", "- foo\n\n\n  bar", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>"],
    ["li-complex", "1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam", "<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>"],
    ["li-code-blanks", "- Foo\n\n      bar\n\n\n      baz", "<ul>\n<li>\n<p>Foo</p>\n<pre><code>bar\n\n\nbaz\n</code></pre>\n</li>\n</ul>"],
    ["li-9digits", "123456789. ok", "<ol start=\"123456789\">\n<li>ok</li>\n</ol>"],
    ["li-10digits", "1234567890. not ok", "<p>1234567890. not ok</p>"],
    ["li-zero", "0. ok", "<ol start=\"0\">\n<li>ok</li>\n</ol>"],
    ["li-leading-zero", "003. ok", "<ol start=\"3\">\n<li>ok</li>\n</ol>"],
    ["li-negative", "-1. not ok", "<p>-1. not ok</p>"],
    ["li-code-in", "- foo\n\n      bar", "<ul>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ul>"],
    ["li-start10-code", "  10.  foo\n\n           bar", "<ol start=\"10\">\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ol>"],
    ["li-starts-with-code", "1.     indented code\n\n   paragraph\n\n       more code", "<ol>\n<li>\n<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>"],
    ["li-starts-with-code2", "1.      indented code\n\n   paragraph\n\n       more code", "<ol>\n<li>\n<pre><code> indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>"],
    ["li-wide-then-para", "-    foo\n\n  bar", "<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>"],
    ["li-blank-start", "-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz", "<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>\n<pre><code>baz\n</code></pre>\n</li>\n</ul>"],
    ["li-blank-start-spaces", "-   \n  foo", "<ul>\n<li>foo</li>\n</ul>"],
    ["li-blank-then-blank", "-\n\n  foo", "<ul>\n<li></li>\n</ul>\n<p>foo</p>"],
    ["li-empty-middle", "- foo\n-\n- bar", "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>"],
    ["li-empty-ordered", "1. foo\n2.\n3. bar", "<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>"],
    ["li-star-alone", "*", "<ul>\n<li></li>\n</ul>"],
    ["li-empty-no-interrupt", "foo\n*\n\nfoo\n1.", "<p>foo\n*</p>\n<p>foo\n1.</p>"],
    ["li-lazy", "  1.  A paragraph\nwith two lines.\n\n          indented code\n\n      > A block quote.", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>"],
    ["li-lazy-bq", "> 1. > Blockquote\ncontinued here.", "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>"],
    ["li-nested4", "- foo\n  - bar\n    - baz\n      - boo", "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz\n<ul>\n<li>boo</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>"],
    ["li-not-nested", "- foo\n - bar\n  - baz\n   - boo", "<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz</li>\n<li>boo</li>\n</ul>"],
    ["li-paren-nest", "10) foo\n    - bar", "<ol start=\"10\">\n<li>foo\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>"],
    ["li-paren-no-nest", "10) foo\n   - bar", "<ol start=\"10\">\n<li>foo</li>\n</ol>\n<ul>\n<li>bar</li>\n</ul>"],
    ["li-direct-nest", "- - foo", "<ul>\n<li>\n<ul>\n<li>foo</li>\n</ul>\n</li>\n</ul>"],
    ["li-direct-nest2", "1. - 2. foo", "<ol>\n<li>\n<ul>\n<li>\n<ol start=\"2\">\n<li>foo</li>\n</ol>\n</li>\n</ul>\n</li>\n</ol>"],
    ["li-headings", "- # Foo\n- Bar\n  ---\n  baz", "<ul>\n<li>\n<h1>Foo</h1>\n</li>\n<li>\n<h2>Bar</h2>\nbaz</li>\n</ul>"],

    // ── Lists ──
    ["list-change-bullet", "- foo\n- bar\n+ baz", "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n</ul>"],
    ["list-change-delim", "1. foo\n2. bar\n3) baz", "<ol>\n<li>foo</li>\n<li>bar</li>\n</ol>\n<ol start=\"3\">\n<li>baz</li>\n</ol>"],
    ["list-interrupt", "Foo\n- bar\n- baz", "<p>Foo</p>\n<ul>\n<li>bar</li>\n<li>baz</li>\n</ul>"],
    ["list-14-no-interrupt", "The number of windows in my house is\n14.  The number of doors is 6.", "<p>The number of windows in my house is\n14.  The number of doors is 6.</p>"],
    ["list-1-interrupts", "The number of windows in my house is\n1.  The number of doors is 6.", "<p>The number of windows in my house is</p>\n<ol>\n<li>The number of doors is 6.</li>\n</ol>"],
    ["list-loose-blanks", "- foo\n\n- bar\n\n\n- baz", "<ul>\n<li>\n<p>foo</p>\n</li>\n<li>\n<p>bar</p>\n</li>\n<li>\n<p>baz</p>\n</li>\n</ul>"],
    ["list-nested-blank", "- foo\n  - bar\n    - baz\n\n\n      bim", "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>\n<p>baz</p>\n<p>bim</p>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>"],
    ["list-comment-separates", "- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim", "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n<li>bim</li>\n</ul>"],
    ["list-ragged", "- a\n - b\n  - c\n   - d\n  - e\n - f\n- g", "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n<li>g</li>\n</ul>"],
    ["list-ragged-ordered", "1. a\n\n  2. b\n\n   3. c", "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ol>"],
    ["list-ragged-lazy", "- a\n - b\n  - c\n   - d\n    - e", "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d\n- e</li>\n</ul>"],
    ["list-ragged-code", "1. a\n\n  2. b\n\n    3. c", "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ol>\n<pre><code>3. c\n</code></pre>"],
    ["list-loose-middle", "- a\n- b\n\n- c", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ul>"],
    ["list-loose-empty", "* a\n*\n\n* c", "<ul>\n<li>\n<p>a</p>\n</li>\n<li></li>\n<li>\n<p>c</p>\n</li>\n</ul>"],
    ["list-loose-inner", "- a\n- b\n\n  c\n- d", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>"],
    ["list-loose-ref", "- a\n- b\n\n  [ref]: /url\n- d", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>"],
    ["list-tight-fence-blanks", "- a\n- ```\n  b\n\n\n  ```\n- c", "<ul>\n<li>a</li>\n<li>\n<pre><code>b\n\n\n</code></pre>\n</li>\n<li>c</li>\n</ul>"],
    ["list-inner-loose", "- a\n  - b\n\n    c\n- d", "<ul>\n<li>a\n<ul>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n</ul>\n</li>\n<li>d</li>\n</ul>"],
    ["list-tight-bq", "* a\n  > b\n  >\n* c", "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n</li>\n<li>c</li>\n</ul>"],
    ["list-tight-bq-fence", "- a\n  > b\n  ```\n  c\n  ```\n- d", "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n<pre><code>c\n</code></pre>\n</li>\n<li>d</li>\n</ul>"],
    ["list-loose-fence-para", "1. ```\n   foo\n   ```\n\n   bar", "<ol>\n<li>\n<pre><code>foo\n</code></pre>\n<p>bar</p>\n</li>\n</ol>"],
    ["list-outer-loose", "* foo\n  * bar\n\n  baz", "<ul>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n<p>baz</p>\n</li>\n</ul>"],
    ["list-outer-loose2", "- a\n  - b\n  - c\n\n- d\n  - e\n  - f", "<ul>\n<li>\n<p>a</p>\n<ul>\n<li>b</li>\n<li>c</li>\n</ul>\n</li>\n<li>\n<p>d</p>\n<ul>\n<li>e</li>\n<li>f</li>\n</ul>\n</li>\n</ul>"],

    // ── Backslash escapes ──
    ["esc-many", "\\*not emphasized*\n\\<br/> not a tag\n\\[not a link](/foo)\n\\`not code`\n1\\. not a list\n\\* not a list\n\\# not a heading\n\\[foo]: /url \"not a reference\"\n\\&ouml; not a character entity", "<p>*not emphasized*\n&lt;br/&gt; not a tag\n[not a link](/foo)\n`not code`\n1. not a list\n* not a list\n# not a heading\n[foo]: /url &quot;not a reference&quot;\n&amp;ouml; not a character entity</p>"],
    ["esc-not-punct", "\\\t\\A\\a\\ \\3\\φ\\«", "<p>\\\t\\A\\a\\ \\3\\φ\\«</p>"],
    ["esc-in-code", "`` \\[\\` ``", "<p><code>\\[\\`</code></p>"],
    ["esc-bracket-line", "\\[x\\] is the interval notation here, not math", "<p>[x] is the interval notation here, not math</p>"],

    // ── Emphasis ──
    ["em-1", "*foo bar*", "<p><em>foo bar</em></p>"],
    ["em-2", "a * foo bar*", "<p>a * foo bar*</p>"],
    ["em-3", "a*\"foo\"*", "<p>a*&quot;foo&quot;*</p>"],
    ["em-5", "foo*bar*", "<p>foo<em>bar</em></p>"],
    ["em-6", "5*6*78", "<p>5<em>6</em>78</p>"],
    ["em-u-intraword", "foo_bar_", "<p>foo_bar_</p>"],
    ["em-u-digits", "5_6_78", "<p>5_6_78</p>"],
    ["em-u-cyrillic", "пристаням_стремятся_", "<p>пристаням_стремятся_</p>"],
    ["em-u-quotes", "aa_\"bb\"_cc", "<p>aa_&quot;bb&quot;_cc</p>"],
    ["em-u-paren", "foo-_(bar)_", "<p>foo-<em>(bar)</em></p>"],
    ["em-mismatch", "_foo*", "<p>_foo*</p>"],
    ["em-space-before-close", "*foo bar *", "<p>*foo bar *</p>"],
    ["em-nested-paren", "*(*foo*)*", "<p><em>(<em>foo</em>)</em></p>"],
    ["em-u-nested-paren", "_(_foo_)_", "<p><em>(<em>foo</em>)</em></p>"],
    ["em-u-intra", "_foo_bar_baz_", "<p><em>foo_bar_baz</em></p>"],
    ["strong-commas", "__foo, __bar__, baz__", "<p><strong>foo, <strong>bar</strong>, baz</strong></p>"],
    ["strong-gompho", "**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**", "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>"],
    ["strong-quote-em", "**foo \"*bar*\" foo**", "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>"],
    ["strong-u-intra", "__foo__bar__baz__", "<p><strong>foo__bar__baz</strong></p>"],
    ["em-u-strong-in", "__foo_ bar_", "<p><em><em>foo</em> bar</em></p>"],
    ["em-in-em", "*foo *bar**", "<p><em>foo <em>bar</em></em></p>"],
    ["em-strong-intra", "*foo**bar**baz*", "<p><em>foo<strong>bar</strong>baz</em></p>"],
    ["em-rule3", "*foo**bar*", "<p><em>foo**bar</em></p>"],
    ["em-triple1", "***foo** bar*", "<p><em><strong>foo</strong> bar</em></p>"],
    ["em-triple2", "*foo **bar***", "<p><em>foo <strong>bar</strong></em></p>"],
    ["em-triple3", "*foo**bar***", "<p><em>foo<strong>bar</strong></em></p>"],
    ["em-triple4", "foo***bar***baz", "<p>foo<em><strong>bar</strong></em>baz</p>"],
    ["em-six-nine", "foo******bar*********baz", "<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>"],
    ["em-deep", "*foo **bar *baz* bim** bop*", "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>"],
    ["em-link", "*foo [*bar*](/url)*", "<p><em>foo <a href=\"/url\"><em>bar</em></a></em></p>"],
    ["em-not-empty", "** is not an empty emphasis", "<p>** is not an empty emphasis</p>"],
    ["strong-deep", "**foo *bar **baz**\nbim* bop**", "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>"],
    ["em-escaped-star", "foo *\\**", "<p>foo <em>*</em></p>"],
    ["em-underscore-in", "foo *_*", "<p>foo <em>_</em></p>"],
    ["em-left1", "**foo*", "<p>*<em>foo</em></p>"],
    ["em-left2", "*foo**", "<p><em>foo</em>*</p>"],
    ["em-left3", "***foo**", "<p>*<strong>foo</strong></p>"],
    ["em-left4", "****foo*", "<p>***<em>foo</em></p>"],
    ["em-left5", "**foo***", "<p><strong>foo</strong>*</p>"],
    ["em-left6", "*foo****", "<p><em>foo</em>***</p>"],
    ["em-double", "*_foo_*", "<p><em><em>foo</em></em></p>"],
    ["em-quad", "****foo****", "<p><strong><strong>foo</strong></strong></p>"],
    ["em-triple-both", "***foo***", "<p><em><strong>foo</strong></em></p>"],
    ["em-five-u", "_____foo_____", "<p><em><strong><strong>foo</strong></strong></em></p>"],
    ["em-overlap", "*foo _bar* baz_", "<p><em>foo _bar</em> baz_</p>"],
    ["em-overlap2", "*foo __bar *baz bim__ bam*", "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>"],
    ["em-unmatched-strong", "**foo **bar baz**", "<p>**foo <strong>bar baz</strong></p>"],
    ["em-link-precedence", "*[bar*](/url)", "<p>*<a href=\"/url\">bar*</a></p>"],
    ["em-code-precedence", "*a `*`*", "<p><em>a <code>*</code></em></p>"],
    ["em-autolink-precedence", "**a<http://foo.bar/?q=**>", "<p>**a<a href=\"http://foo.bar/?q=**\">http://foo.bar/?q=**</a></p>"],

    // ── Code spans ──
    ["code-1", "`` foo ` bar ``", "<p><code>foo ` bar</code></p>"],
    ["code-2", "` `` `", "<p><code>``</code></p>"],
    ["code-3", "`  ``  `", "<p><code> `` </code></p>"],
    ["code-4", "` a`", "<p><code> a</code></p>"],
    ["code-only-spaces", "` `\n`  `", "<p><code> </code>\n<code>  </code></p>"],
    ["code-newlines", "``\nfoo\nbar  \nbaz\n``", "<p><code>foo bar   baz</code></p>"],
    ["code-backslash", "`foo\\`bar`", "<p><code>foo\\</code>bar`</p>"],
    ["code-not-link", "[not a `link](/foo`)", "<p>[not a <code>link](/foo</code>)</p>"],
    ["code-autolink", "<http://foo.bar.`baz>`", "<p><a href=\"http://foo.bar.`baz\">http://foo.bar.`baz</a>`</p>"],
    ["code-unmatched", "```foo``", "<p>```foo``</p>"],
    ["code-unmatched2", "`foo``bar``", "<p>`foo<code>bar</code></p>"],

    // ── Links ──
    ["link-title", "[link](/uri \"title\")", "<p><a href=\"/uri\" title=\"title\">link</a></p>"],
    ["link-empty-dest", "[link]()", "<p><a href=\"\">link</a></p>"],
    ["link-empty-angle", "[link](<>)", "<p><a href=\"\">link</a></p>"],
    ["link-space", "[link](/my uri)", "<p>[link](/my uri)</p>"],
    ["link-angle-space", "[link](</my uri>)", "<p><a href=\"/my uri\">link</a></p>"],
    ["link-newline", "[link](foo\nbar)", "<p>[link](foo\nbar)</p>"],
    ["link-angle-paren", "[a](<b)c>)", "<p><a href=\"b)c\">a</a></p>"],
    ["link-escaped-parens", "[link](\\(foo\\))", "<p><a href=\"(foo)\">link</a></p>"],
    ["link-balanced", "[link](foo(and(bar)))", "<p><a href=\"foo(and(bar))\">link</a></p>"],
    ["link-unbalanced", "[link](foo(and(bar))", "<p>[link](foo(and(bar))</p>"],
    ["link-titles", "[link](/url \"title\")\n[link](/url 'title')\n[link](/url (title))", "<p><a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a></p>"],
    ["link-title-escapes", "[link](/url \"title \\\"&quot;\")", "<p><a href=\"/url\" title=\"title &quot;&quot;\">link</a></p>"],
    ["link-title-unescaped-quote", "[link](/url \"title \"and\" title\")", "<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>"],
    ["link-ws", "[link](   /uri\n  \"title\"  )", "<p><a href=\"/uri\" title=\"title\">link</a></p>"],
    ["link-space-between", "[link] (/uri)", "<p>[link] (/uri)</p>"],
    ["link-nested-brackets", "[link [foo [bar]]](/uri)", "<p><a href=\"/uri\">link [foo [bar]]</a></p>"],
    ["link-unbalanced-text", "[link] bar](/uri)", "<p>[link] bar](/uri)</p>"],
    ["link-inner", "[link [bar](/uri)", "<p>[link <a href=\"/uri\">bar</a></p>"],
    ["link-image-in", "[![moon](moon.jpg)](/uri)", "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>"],
    ["link-no-nest", "[foo [bar](/uri)](/uri)", "<p>[foo <a href=\"/uri\">bar</a>](/uri)</p>"],
    ["link-no-nest2", "[foo *[bar [baz](/uri)](/uri)*](/uri)", "<p>[foo <em>[bar <a href=\"/uri\">baz</a>](/uri)</em>](/uri)</p>"],
    ["link-img-nest", "![[[foo](uri1)](uri2)](uri3)", "<p><img src=\"uri3\" alt=\"[foo](uri2)\" /></p>"],
    ["link-em-split", "*[foo*](/uri)", "<p>*<a href=\"/uri\">foo*</a></p>"],
    ["link-em-dest", "[foo *bar](baz*)", "<p><a href=\"baz*\">foo *bar</a></p>"],
    ["link-em-bracket", "*foo [bar* baz]", "<p><em>foo [bar</em> baz]</p>"],
    ["link-code-precedence", "[foo`](/uri)`", "<p>[foo<code>](/uri)</code></p>"],
    ["ref-basic", "[foo][bar]\n\n[bar]: /url \"title\"", "<p><a href=\"/url\" title=\"title\">foo</a></p>"],
    ["ref-case", "[foo][BaR]\n\n[bar]: /url", "<p><a href=\"/url\">foo</a></p>"],
    ["ref-unicode-case", "[ẞ]\n\n[SS]: /url", "<p><a href=\"/url\">ẞ</a></p>"],
    ["ref-multiline-label", "[Foo\n  bar]: /url\n\n[Baz][Foo bar]", "<p><a href=\"/url\">Baz</a></p>"],
    ["ref-space-between", "[foo] [bar]\n\n[bar]: /url \"title\"", "<p>[foo] <a href=\"/url\" title=\"title\">bar</a></p>"],
    ["ref-first-wins", "[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]", "<p><a href=\"/url1\">bar</a></p>"],
    ["ref-collapsed", "[*foo* bar][]\n\n[*foo* bar]: /url \"title\"", "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>"],
    ["ref-shortcut-brackets", "[[*foo* bar]]\n\n[*foo* bar]: /url \"title\"", "<p>[<a href=\"/url\" title=\"title\"><em>foo</em> bar</a>]</p>"],
    ["ref-escaped", "\\[foo]\n\n[foo]: /url \"title\"", "<p>[foo]</p>"],
    ["ref-not-link-paren", "[foo](not a link)\n\n[foo]: /url1", "<p><a href=\"/url1\">foo</a>(not a link)</p>"],
    ["ref-three", "[foo][bar][baz]\n\n[baz]: /url", "<p>[foo]<a href=\"/url\">bar</a></p>"],
    ["ref-three2", "[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2", "<p><a href=\"/url2\">foo</a><a href=\"/url1\">baz</a></p>"],
    ["ref-def-title-next-line", "[foo]: /url\n\"title\"\n\n[foo]", "<p><a href=\"/url\" title=\"title\">foo</a></p>"],
    ["ref-def-dest-next-line", "[foo]:\n/url\n\n[foo]", "<p><a href=\"/url\">foo</a></p>"],

    // ── Images ──
    ["img-alt-plain", "![foo *bar*]\n\n[foo *bar*]: train.jpg \"train & tracks\"", "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>"],
    ["img-nested-img", "![foo ![bar](/url)](/url2)", "<p><img src=\"/url2\" alt=\"foo bar\" /></p>"],
    ["img-empty-alt", "![](/url)", "<p><img src=\"/url\" alt=\"\" /></p>"],

    // ── Autolinks ──
    ["auto-1", "<http://foo.bar.baz>", "<p><a href=\"http://foo.bar.baz\">http://foo.bar.baz</a></p>"],
    ["auto-irc", "<irc://foo.bar:2233/baz>", "<p><a href=\"irc://foo.bar:2233/baz\">irc://foo.bar:2233/baz</a></p>"],
    ["auto-space", "<https://foo.bar/baz bim>", "<p>&lt;https://foo.bar/baz bim&gt;</p>"],
    ["auto-email", "<foo+special@Bar.baz-bar0.com>", "<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>"],
    ["auto-empty", "<>", "<p>&lt;&gt;</p>"],
    ["auto-short-scheme", "<m:abc>", "<p>&lt;m:abc&gt;</p>"],
    ["auto-no-scheme", "<foo.bar.baz>", "<p>&lt;foo.bar.baz&gt;</p>"],
    ["gfm-www", "Visit www.commonmark.org/help for more information.", "<p>Visit <a href=\"http://www.commonmark.org/help\">www.commonmark.org/help</a> for more information.</p>"],
    ["gfm-trailing-dot", "Visit www.commonmark.org.\n\nVisit www.commonmark.org/a.b.", "<p>Visit <a href=\"http://www.commonmark.org\">www.commonmark.org</a>.</p>\n<p>Visit <a href=\"http://www.commonmark.org/a.b\">www.commonmark.org/a.b</a>.</p>"],
    ["gfm-parens", "www.google.com/search?q=Markup+(business)\n\nwww.google.com/search?q=Markup+(business)))\n\n(www.google.com/search?q=Markup+(business))\n\n(www.google.com/search?q=Markup+(business)", "<p><a href=\"http://www.google.com/search?q=Markup+(business)\">www.google.com/search?q=Markup+(business)</a></p>\n<p><a href=\"http://www.google.com/search?q=Markup+(business)\">www.google.com/search?q=Markup+(business)</a>))</p>\n<p>(<a href=\"http://www.google.com/search?q=Markup+(business)\">www.google.com/search?q=Markup+(business)</a>)</p>\n<p>(<a href=\"http://www.google.com/search?q=Markup+(business)\">www.google.com/search?q=Markup+(business)</a></p>"],
    ["gfm-inner-paren", "www.google.com/search?q=(business))+ok", "<p><a href=\"http://www.google.com/search?q=(business))+ok\">www.google.com/search?q=(business))+ok</a></p>"],
    ["gfm-entity-end", "www.google.com/search?q=commonmark&hl=en\n\nwww.google.com/search?q=commonmark&hl;", "<p><a href=\"http://www.google.com/search?q=commonmark&amp;hl=en\">www.google.com/search?q=commonmark&amp;hl=en</a></p>\n<p><a href=\"http://www.google.com/search?q=commonmark\">www.google.com/search?q=commonmark</a>&amp;hl;</p>"],
    ["gfm-lt", "www.commonmark.org/he<lp", "<p><a href=\"http://www.commonmark.org/he\">www.commonmark.org/he</a>&lt;lp</p>"],
    ["gfm-http", "http://commonmark.org\n\n(Visit https://encrypted.google.com/search?q=Markup+(business))", "<p><a href=\"http://commonmark.org\">http://commonmark.org</a></p>\n<p>(Visit <a href=\"https://encrypted.google.com/search?q=Markup+(business)\">https://encrypted.google.com/search?q=Markup+(business)</a>)</p>"],
    ["gfm-email", "foo@bar.baz", "<p><a href=\"mailto:foo@bar.baz\">foo@bar.baz</a></p>"],
    ["gfm-email-plus", "hello@mail+xyz.example isn't valid, but hello+xyz@mail.example is.", "<p>hello@mail+xyz.example isn't valid, but <a href=\"mailto:hello+xyz@mail.example\">hello+xyz@mail.example</a> is.</p>"],
    ["gfm-url-underscores", "See https://example.com/a_b_c_d and https://example.com/x*y*z.", "<p>See <a href=\"https://example.com/a_b_c_d\">https://example.com/a_b_c_d</a> and <a href=\"https://example.com/x*y*z\">https://example.com/x*y*z</a>.</p>"],
    ["gfm-url-in-strong", "**https://example.com/docs**", "<p><strong><a href=\"https://example.com/docs\">https://example.com/docs</a></strong></p>"],
    ["gfm-url-trailing-paren-text", "(see https://example.com)", "<p>(see <a href=\"https://example.com\">https://example.com</a>)</p>"],

    // ── Hard breaks ──
    ["br-1", "foo  \nbaz", "<p>foo<br />\nbaz</p>"],
    ["br-2", "foo\\\nbaz", "<p>foo<br />\nbaz</p>"],
    ["br-3", "foo       \nbaz", "<p>foo<br />\nbaz</p>"],
    ["br-4", "foo  \n     bar", "<p>foo<br />\nbar</p>"],
    ["br-em", "*foo  \nbar*", "<p><em>foo<br />\nbar</em></p>"],
    ["br-code", "`code  \nspan`", "<p><code>code   span</code></p>"],
    ["br-end-backslash", "foo\\", "<p>foo\\</p>"],
    ["br-end-spaces", "foo  ", "<p>foo</p>"],
    ["br-heading-backslash", "### foo\\", "<h3>foo\\</h3>"],
    ["soft-1", "foo \n baz", "<p>foo\nbaz</p>"],

    // ── Entities ──
    ["ent-common", "&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;", "<p>\u00a0 &amp; © Æ Ď\n¾ ℋ ⅆ\n∲ ≧̸</p>"],
    ["ent-numeric", "&#35; &#1234; &#992; &#0;", "<p># Ӓ Ϡ \ufffd</p>"],
    ["ent-not", "&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;", "<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>"],

    // ── GFM tables ──
    ["tbl-198", "| foo | bar |\n| --- | --- |\n| baz | bim |", "<table>\n<thead>\n<tr>\n<th>foo</th>\n<th>bar</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>baz</td>\n<td>bim</td>\n</tr>\n</tbody>\n</table>"],
    ["tbl-199", "| abc | defghi |\n:-: | -----------:\nbar | baz", "<table>\n<thead>\n<tr>\n<th align=\"center\">abc</th>\n<th align=\"right\">defghi</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td align=\"center\">bar</td>\n<td align=\"right\">baz</td>\n</tr>\n</tbody>\n</table>"],
    ["tbl-200 escaped pipes in code and strong", "| f\\|oo  |\n| ------ |\n| b `\\|` az |\n| b **\\|** im |", "<table>\n<thead>\n<tr>\n<th>f|oo</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>b <code>|</code> az</td>\n</tr>\n<tr>\n<td>b <strong>|</strong> im</td>\n</tr>\n</tbody>\n</table>"],
    ["tbl-201", "| abc | def |\n| --- | --- |\n| bar | baz |\n> bar", "<table>\n<thead>\n<tr>\n<th>abc</th>\n<th>def</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>bar</td>\n<td>baz</td>\n</tr>\n</tbody>\n</table>\n<blockquote>\n<p>bar</p>\n</blockquote>"],
    ["tbl-202", "| abc | def |\n| --- | --- |\n| bar | baz |\nbar\n\nbar", "<table>\n<thead>\n<tr>\n<th>abc</th>\n<th>def</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>bar</td>\n<td>baz</td>\n</tr>\n<tr>\n<td>bar</td>\n<td></td>\n</tr>\n</tbody>\n</table>\n<p>bar</p>"],
    ["tbl-203", "| abc | def |\n| --- |\n| bar |", "<p>| abc | def |\n| --- |\n| bar |</p>"],
    ["tbl-204", "| abc | def |\n| --- | --- |\n| bar |\n| bar | baz | boo |", "<table>\n<thead>\n<tr>\n<th>abc</th>\n<th>def</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>bar</td>\n<td></td>\n</tr>\n<tr>\n<td>bar</td>\n<td>baz</td>\n</tr>\n</tbody>\n</table>"],
    ["tbl-205", "| abc | def |\n| --- | --- |", "<table>\n<thead>\n<tr>\n<th>abc</th>\n<th>def</th>\n</tr>\n</thead>\n</table>"],
    ["tbl-no-outer-pipes", "a | b\n--|--\n1 | 2", "<table>\n<thead>\n<tr>\n<th>a</th>\n<th>b</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n<td>2</td>\n</tr>\n</tbody>\n</table>"],
    ["tbl-hr-after", "| a |\n|---|\n| 1 |\n---", "<table>\n<thead>\n<tr>\n<th>a</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n</tr>\n</tbody>\n</table>\n<hr />"],
    ["tbl-list-after", "| a |\n|---|\n| 1 |\n- item", "<table>\n<thead>\n<tr>\n<th>a</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n</tr>\n</tbody>\n</table>\n<ul>\n<li>item</li>\n</ul>"],
    ["tbl-heading-after", "| a |\n|---|\n| 1 |\n## Next", "<table>\n<thead>\n<tr>\n<th>a</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n</tr>\n</tbody>\n</table>\n<h2>Next</h2>"],
    ["tbl-in-list", "1. Compare:\n\n   | A | B |\n   |---|---|\n   | 1 | 2 |\n\n2. Done", "<ol>\n<li>\n<p>Compare:</p>\n<table>\n<thead>\n<tr>\n<th>A</th>\n<th>B</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n<td>2</td>\n</tr>\n</tbody>\n</table>\n</li>\n<li>\n<p>Done</p>\n</li>\n</ol>"],
    ["tbl-in-bq", "> | A | B |\n> |---|---|\n> | 1 | 2 |", "<blockquote>\n<table>\n<thead>\n<tr>\n<th>A</th>\n<th>B</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>1</td>\n<td>2</td>\n</tr>\n</tbody>\n</table>\n</blockquote>"],
    ["tbl-delim-no-pipe-single-col", "| a |\n---", "<h2>| a |</h2>"],

    // ── GFM task lists and strikethrough ──
    ["task-279", "- [ ] foo\n- [x] bar", "<ul>\n<li><input type=\"checkbox\" disabled /> foo</li>\n<li><input type=\"checkbox\" checked disabled /> bar</li>\n</ul>"],
    ["task-280", "- [x] foo\n  - [ ] bar\n  - [x] baz\n- [ ] bim", "<ul>\n<li><input type=\"checkbox\" checked disabled /> foo\n<ul>\n<li><input type=\"checkbox\" disabled /> bar</li>\n<li><input type=\"checkbox\" checked disabled /> baz</li>\n</ul>\n</li>\n<li><input type=\"checkbox\" disabled /> bim</li>\n</ul>"],
    ["task-ordered", "1. [x] one\n2. [ ] two", "<ol>\n<li><input type=\"checkbox\" checked disabled /> one</li>\n<li><input type=\"checkbox\" disabled /> two</li>\n</ol>"],
    ["strike-491", "~~Hi~~ Hello, ~there~ world!", "<p><del>Hi</del> Hello, <del>there</del> world!</p>"],
    ["strike-492", "This ~~has a\n\nnew paragraph~~.", "<p>This ~~has a</p>\n<p>new paragraph~~.</p>"],
    ["strike-493", "This will ~~~not~~~ strike.", "<p>This will ~~~not~~~ strike.</p>"],
    ["strike-approx", "It takes ~5 minutes and ~10 MB.", "<p>It takes ~5 minutes and ~10 MB.</p>"],
    ["gfm-url-underscore-segment", "Docs: https://example.com/_private_/x", "<p>Docs: <a href=\"https://example.com/_private_/x\">https://example.com/_private_/x</a></p>"],
    ["gfm-url-dollar", "Pricing at https://example.com/$plan$/x today", "<p>Pricing at <a href=\"https://example.com/$plan$/x\">https://example.com/$plan$/x</a> today</p>"],
    // ── Added for the first fix round: addresses as cmark-gfm reads them ──
    ["gfm-www-underscore-segment", "Visit www.example.com/_private_/x.", "<p>Visit <a href=\"http://www.example.com/_private_/x\">www.example.com/_private_/x</a>.</p>"],
    ["gfm-url-semicolon", "See https://example.com/a; then www.example.com/b&hl;", "<p>See <a href=\"https://example.com/a\">https://example.com/a</a>; then <a href=\"http://www.example.com/b\">www.example.com/b</a>&amp;hl;</p>"],
    ["gfm-invalid-domain", "www.a_b.example_c and http://a_b.example_c", "<p>www.a_b.example_c and http://a_b.example_c</p>"],
];
