import { useRef, useState } from 'react';
import { navigateTo } from '@/lib/navigation';
import { ArrowDown, ArrowRight, Braces, File, FileText, Image, Layers, Music2, Plus, Search, ShieldCheck, Sparkles, Star, Workflow, X } from 'lucide-react';
import { useExperience } from '@/lib/experience';
import { useFavorites } from '@/hooks/useFavorites';
import { formatRelativeTime } from '@/hooks/useHistory';
import { formatFileSize } from '@/lib/api';
import { storeFileHandoffs, clearFileHandoffs } from '@/lib/file-handoff';
import { ToolIcon, FavoriteButton } from '../daylight/consumer/ConsumerChrome';
import { catalogue, commonSlugs, fileSuggestions, savedWorkflows, searchTools, toolBySlug, toolHref, workflowHref, type ConsumerTool, type RecentTool } from '../daylight/consumer/catalogue';

function ToolLink({tool}: {tool:ConsumerTool}) {return <div className="pt-tool-link"><a href={toolHref(tool)}><span className="pt-tool-icon"><ToolIcon tool={tool} size={23}/></span><span><b>{tool.name}</b><small>{tool.description}</small></span><ArrowRight size={19}/></a><FavoriteButton slug={tool.slug}/></div>;}
const groups=[{category:'organize',name:'PDF',text:'Bring your documents together.',icon:FileText,slugs:['merge-pdf','compress-pdf','pdf-to-word'],cls:'pdf'}, {category:'image',name:'Image',text:'A fresh look for every pixel.',icon:Image,slugs:['resize-crop-image','remove-background','image-converter'],cls:'image'}, {category:'developer',name:'Text & code',text:'Untangle. Format. Make sense.',icon:Braces,slugs:['markdown-html','markdown-to-pdf','json-xml-formatter'],cls:'code'}, {category:'video-audio',name:'Audio & video',text:'Find your rhythm.',icon:Music2,slugs:['compress-video','audio-converter','transcribe-audio'],cls:'media'}];

export function ExperienceHome({history,onClearHistory,files,onFiles,onBrowse}: {history:RecentTool[];onClearHistory:()=>void;files:File[];onFiles:(files:File[])=>void;onBrowse:(query:string)=>void}) {
  const {experience,resolved}=useExperience();
  const input=useRef<HTMLInputElement>(null);
  const [query,setQuery]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [manage,setManage]=useState(false);
  const {favorites,toggle,reorder}=useFavorites();
  const workflows=savedWorkflows();
  const pinned=favorites.map(slug=>toolBySlug.get(slug)).filter((x):x is ConsumerTool=>!!x);
  const shown=query.trim()?searchTools(query).slice(0,12):commonSlugs.map(slug=>toolBySlug.get(slug)).filter((x):x is ConsumerTool=>!!x);
  const suggestions=fileSuggestions(files);
  async function openFiles(tool:ConsumerTool) {if(busy)return;setBusy(true);setError('');try{await storeFileHandoffs(files,tool.slug);navigateTo(toolHref(tool));onFiles([]);}catch{setError('We couldn’t open that selection. Your files are still here. Please try again.');}finally{setBusy(false);}}
  return <div className="pt-home">
    <section className="pt-hero">
      <div className="pt-hero-copy"><span className="pt-eyebrow"><span/>{experience==='air'?'A little space to get things done':'YOUR EVERYDAY TOOLKIT, WITH A TWIST'}</span><h1>{experience==='air'?<>Your files.<br/>A little lighter.</>:<>Small tasks.<br/><em>Big relief.</em></>}</h1><p>{experience==='air'?'A thoughtful home for your PDFs, images, text and more. Find your tool, finish your task, get back to your day.':'A whole box of clever tools for the things between you and the fun stuff. Let’s make a little room.'}</p><form className="pt-home-search" role="search" onSubmit={event=>{event.preventDefault();onBrowse(query);}}><Search size={22}/><input aria-label="Find a tool or task" value={query} onChange={event=>setQuery(event.target.value)} placeholder="What would you like to do?"/><button type="submit" aria-label="Search all tools"><ArrowRight size={20}/></button></form><div className="pt-hero-actions"><button type="button" className="pt-button pt-primary" onClick={()=>input.current?.click()}><Plus size={20}/>Start with a file</button><a href="/tools" className="pt-text-link">Explore {catalogue.length} tools <ArrowRight size={17}/></a></div><small className="pt-hero-note"><ShieldCheck size={15}/>Free to use. No account needed.</small><input type="file" multiple hidden ref={input} aria-label="Choose files on this device" onChange={event=>{if(event.target.files?.length)onFiles(Array.from(event.target.files));event.target.value='';}}/></div>
      <div className="pt-air-art" aria-hidden="true"><img src={resolved==='dark'?'/experience/air-graphite.png':'/experience/air-mist.png'} alt=""/><div className="pt-floating-note"><span><FileText size={19}/></span><div>A place for every file<small>A little order. A lot of possibility.</small></div><ShieldCheck size={19}/></div></div>
      <div className="pt-play-art" aria-hidden="true"><div className="pt-play-note pt-play-note-one"><FileText size={38}/><b>Less<br/>paperwork.</b><i/><i/><i/></div><div className="pt-play-note pt-play-note-two"><Image size={32}/><div className="pt-picture-sun"/><div className="pt-picture-hills"/></div><div className="pt-play-sticker">Make room<br/>for the good stuff <span>↗</span></div><span className="pt-play-spark">✳</span><div className="pt-play-code">{'{'}<small>life: simpler</small>{'}'}</div></div>
    </section>
    {files.length>0&&<section className="pt-selection pt-panel" aria-labelledby="selection-heading"><div className="pt-section-heading"><div><span className="pt-eyebrow">READY WHEN YOU ARE</span><h2 id="selection-heading">What happens next?</h2><p>{files.length} {files.length === 1 ? "file" : "files"} selected on this device. Nothing uploaded yet.</p></div><button className="pt-text-button" onClick={()=>{clearFileHandoffs();onFiles([]);setError('');}}>Clear selection</button></div><ul className="pt-file-list">{files.map((file,index)=><li key={file.name+index}><File size={20}/><span><b>{file.name}</b><small>{formatFileSize(file.size)}</small></span><button className="pt-icon-button" aria-label={'Remove '+file.name} onClick={()=>onFiles(files.filter((_,i)=>i!==index))}><X size={17}/></button></li>)}</ul>{files.length>25?<p role="alert">Choose up to 25 files for a handoff. Remove some files or open Batch.</p>:<div className="pt-selection-actions">{suggestions.map(tool=><button className="pt-button" key={tool.slug} disabled={busy} onClick={()=>void openFiles(tool)}>{tool.name}<ArrowRight size={17}/></button>)}{!suggestions.length&&<p>Browse the catalogue to find a tool for these file types. Your selection stays here.</p>}</div>}{error&&<p role="alert">{error}</p>}</section>}
    <section className="pt-categories"><div className="pt-section-heading"><div><span className="pt-eyebrow">PICK YOUR KIND OF PRODUCTIVE</span><h2>What are we working on?</h2></div><a href="/tools" className="pt-text-link">All tools <ArrowRight size={18}/></a></div><div className="pt-category-grid">{groups.map(group=><article className={'pt-category pt-category-'+group.cls} key={group.cls}><a className="pt-category-title" href={'/tools?cat='+group.category}><group.icon size={27}/><h3>{group.name}</h3><ArrowRight size={24}/></a><p>{group.text}</p><div className="pt-category-shape" aria-hidden="true"><group.icon strokeWidth={1.2}/></div><div className="pt-category-tools">{group.slugs.map(slug=>toolBySlug.get(slug)).filter((x):x is ConsumerTool=>!!x).slice(0,3).map(tool=><a href={toolHref(tool)} key={tool.slug}>{tool.name}<ArrowRight size={14}/></a>)}<a href={'/tools?cat='+group.category}>See the collection <ArrowRight size={14}/></a></div></article>)}</div></section>
    <div className="pt-home-workspace"><section className="pt-popular"><div className="pt-section-heading"><div><span className="pt-eyebrow">THE EVERYDAY ESSENTIALS</span><h2>{query?'Found for you':'Small tasks, sorted.'}</h2></div><a href="/tools" className="pt-text-link">View all <ArrowRight size={18}/></a></div><div className="pt-tool-grid">{shown.map(tool=><ToolLink key={tool.slug} tool={tool}/>)}</div>{!shown.length&&<div className="pt-empty">No matching tools. Try “image”, “compress” or “PDF”.<button className="pt-text-button" onClick={()=>setQuery('')}>Clear search</button></div>}</section><aside className="pt-recent"><div className="pt-section-heading"><h2>Recently opened</h2><button className="pt-text-button" disabled={!history.length} onClick={onClearHistory}>Clear</button></div>{history.slice(0,4).map(item=>{const tool=toolBySlug.get(item.s);return tool&&<a className="pt-recent-row" key={item.s} href={toolHref(tool)}><ToolIcon tool={tool} size={21}/><span><b>{tool.name}</b><small>{formatRelativeTime(item.ts)}</small></span><ArrowRight size={16}/></a>;})}{!history.length&&<div className="pt-empty"><span className="pt-empty-orbit"><Workflow size={28}/></span><b>Your next task starts here.</b><p>Tools you open appear here. This list saves no files or filenames.</p></div>}</aside></div>
    <section className="pt-favorites"><div className="pt-section-heading"><div><span className="pt-eyebrow">A SPACE THAT FEELS LIKE YOU</span><h2>Your favorites, within reach.</h2></div><button className="pt-button" onClick={()=>setManage(!manage)}><Star size={17}/>{manage?'Done':'Manage favorites'}</button></div><div className="pt-tool-grid">{pinned.map((tool,index)=><div key={tool.slug}><ToolLink tool={tool}/>{manage&&<div className="pt-reorder"><button disabled={index===0} onClick={()=>reorder(index,index-1)}>Move earlier</button><button disabled={index===pinned.length-1} onClick={()=>reorder(index,index+1)}>Move later</button></div>}</div>)}</div>{!pinned.length&&<p className="pt-muted">Tap the star beside a tool to keep it close. Your favorites stay on this device.</p>}{manage&&<div className="pt-pin-picker"><label htmlFor="pt-pin-query">Find a tool to pin</label><input id="pt-pin-query" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search your toolkit"/><div>{searchTools(query).slice(0,16).map(tool=><button key={tool.slug} aria-pressed={favorites.includes(tool.slug)} onClick={()=>toggle(tool.slug)}>{tool.name}<Star size={15} fill={favorites.includes(tool.slug)?'currentColor':'none'}/></button>)}</div></div>}</section>
    <section className="pt-workflow-feature"><div className="pt-workflow-copy"><span className="pt-eyebrow">A GOOD ROUTINE GOES A LONG WAY</span><h2>Do the whole thing.<br/><em>In one little flow.</em></h2><p>Connect your PDF tools, save the sequence and use it again. Less repeat work, more room in your day.</p><a href="/pipeline" className="pt-button pt-primary">Build a pipeline <ArrowRight size={18}/></a>{workflows.slice(0,2).map((workflow,index)=><a className="pt-saved-flow" key={index} href={workflowHref(workflow)}><Workflow size={16}/>{workflow.name}<small>{workflow.slugs.length} steps</small></a>)}</div><div className="pt-workflow-visual" aria-label="Example workflow: rotate, compress, download">{[[FileText,'01','Rotate pages'],[Layers,'02','Compress PDF'],[ArrowDown,'03','Download result']].map(([Icon,number,label],index)=>{const Component=Icon as typeof FileText;return <div className="pt-flow-step" key={index}><span>{String(number)}</span><Component size={24}/><b>{String(label)}</b><i/></div>;})}<small>Example sequence · choose a file to run</small></div></section>
    <section className="pt-trust-strip"><ShieldCheck size={36}/><div><h2>Know where your files go.</h2><p>On your device when possible. Temporary processing when a server is needed. Clearly explained before you start.</p></div><a className="pt-text-link" href="/trust">Meet your trust center <ArrowRight size={18}/></a></section>
    <div className="pt-next-links"><a href="/batch"><Layers/><span><b>A whole folder to finish?</b><small>Meet batch processing</small></span><ArrowRight/></a><a href="/ai"><Sparkles/><span><b>A little extra help?</b><small>Explore your AI studio</small></span><ArrowRight/></a></div>
  </div>;
}
