import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, X } from 'lucide-react';
import { useToolDefaults } from '@/hooks/useToolDefaults';
import { buildOutputFilename, formatFileSize } from '@/lib/api';
import { ArrangementCanvas } from './media/MediaCanvases';
import { MediaBusy, MediaChoices, MediaField, MediaFinished, MediaLayout, MediaRange, MediaRun, MediaUpload } from './media/MediaStudio';
import { useMediaJob } from './media/useMediaJob';
export function CollageUI(){const[config,,{setField}]=useToolDefaults('make-collage',{columns:3,autoColumns:true,spacing:10,bgColor:'#ffffff'});const{columns,autoColumns,spacing,bgColor}=config;const[files,setFiles]=useState<File[]>([]);const job=useMediaJob();const[drag,setDrag]=useState<number|null>(null);useEffect(()=>{if(autoColumns&&files.length)setField('columns',Math.max(1,Math.min(6,Math.ceil(Math.sqrt(files.length)))));},[files.length,autoColumns,setField]);const move=(from:number,to:number)=>{if(job.busy||to<0||to>=files.length)return;setFiles(list=>{const next=[...list];const[item]=next.splice(from,1);next.splice(to,0,item);return next;});};
 if(job.result&&job.status==='done')return <MediaFinished result={job.result} kind="image" title="A little collection, together." onReset={job.reset}/>;
 return <MediaLayout title="Pictures that belong together." busy={job.busy} settings={<><MediaField label="The arrangement"><label className="ms-check"><input type="checkbox" checked={autoColumns} onChange={e=>setField('autoColumns',e.target.checked)}/>Find a balanced grid</label><MediaChoices label="Collage columns" value={columns} onChange={value=>{setField('autoColumns',false);setField('columns',value);}} options={[1,2,3,4,5,6].map(value=>({value,label:`${value} ${value===1?'column':'columns'}`}))}/></MediaField><MediaRange label="Space between photos" value={spacing} min={0} max={100} unit=" px" onChange={value=>setField('spacing',value)}/><MediaField label="Background colour"><label className="sr-only" htmlFor="collage-bg">Collage background colour</label><input id="collage-bg" type="color" value={bgColor} onChange={e=>setField('bgColor',e.target.value)}/></MediaField><MediaRun label="Make the collage" canRun={files.length>=2} busy={job.busy} error={job.error} onRun={()=>job.run({endpoint:'/make-collage',files,params:{columns,spacing,bg_color:bgColor},name:buildOutputFilename(files[0]?.name,'collage','jpg')})}/><p className="ms-caption">At least two images. Photos fit within equal cells without cropping.</p></>}>
 {files.length?<><ArrangementCanvas files={files} columns={columns} spacing={spacing} bgColor={bgColor}/><div className="ms-order-list">{files.map((file,index)=><article key={`${file.name}-${index}`} draggable={!job.busy} onDragStart={()=>setDrag(index)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!=null)move(drag,index);setDrag(null);}}><span className="ms-file-number">{index+1}</span><div><strong>{file.name}</strong><small>{formatFileSize(file.size)}</small></div><button className="ms-icon-button" disabled={job.busy||index===0} aria-label={`Move ${file.name} earlier`} onClick={()=>move(index,index-1)}><ArrowLeft size={14}/></button><button className="ms-icon-button" disabled={job.busy||index===files.length-1} aria-label={`Move ${file.name} later`} onClick={()=>move(index,index+1)}><ArrowRight size={14}/></button><button className="ms-icon-button" disabled={job.busy} aria-label={`Remove ${file.name}`} onClick={()=>setFiles(list=>list.filter((_,i)=>i!==index))}><X size={14}/></button></article>)}</div></>:null}<MediaUpload accepts=".jpg,.jpeg,.png,.webp,.bmp" multiple disabled={job.busy} compact={files.length>0} title={files.length?'Add more photos':'Bring your photos together.'} onFiles={next=>setFiles(list=>[...list,...next])}/>{job.busy&&<><MediaBusy label="Building your collage"/><button className="ms-text" onClick={job.cancel}>Cancel request</button></>}
 </MediaLayout>;
}
