import { useRef, useState } from 'react';
import { ArrowDownToLine, X } from 'lucide-react';
import { buildOutputFilename, downloadBlob, uploadFileGetJson } from '@/lib/api';
import { friendlyError } from '@/lib/utils';
import { useMediaJob } from './media/useMediaJob';
import { ImageComparison, MediaBusy, MediaChoices, MediaField, MediaLayout, MediaPreview, MediaRun, MediaUpload } from "./media/MediaStudio";
import { useMediaUrl } from "./media/media-files";
type Region={x:number;y:number;width:number;height:number};
export function RemoveImageWatermarkUI(){
 const[file,setFile]=useState<File|null>(null);const[regions,setRegions]=useState<Region[]>([]);const[dims,setDims]=useState({w:1,h:1});const[method,setMethod]=useState('telea');const[active,setActive]=useState(0);const[draft,setDraft]=useState<Region|null>(null);const origin=useRef<{x:number;y:number}|null>(null);const url=useMediaUrl(file);const job=useMediaJob();
 const point=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.round(Math.max(0,Math.min(dims.w,(e.clientX-r.left)/r.width*dims.w))),y:Math.round(Math.max(0,Math.min(dims.h,(e.clientY-r.top)/r.height*dims.h)))};};
 const draftAt=(p:{x:number;y:number})=>({x:Math.min(origin.current!.x,p.x),y:Math.min(origin.current!.y,p.y),width:Math.abs(p.x-origin.current!.x),height:Math.abs(p.y-origin.current!.y)});
 const update=(key:keyof Region,value:number)=>setRegions(prev=>prev.map((r,i)=>{if(i!==active)return r;const next={...r,[key]:Math.max(key==='width'||key==='height'?1:0,Math.round(value)||0)};next.x=Math.min(next.x,dims.w-1);next.y=Math.min(next.y,dims.h-1);next.width=Math.min(next.width,dims.w-next.x);next.height=Math.min(next.height,dims.h-next.y);return next;}));
 const resetFile=(next:File)=>{setFile(next);setRegions([]);setActive(0);setDraft(null);job.reset();};
 if(job.result&&job.status==='done')return <MediaLayout title="A cleaner picture." settings={<><MediaField label="Review the reconstructed area" detail="These pixels were rebuilt from their surroundings. The original hidden detail cannot be recovered."/><button className="ms-primary" onClick={()=>downloadBlob(job.result!.blob,job.result!.name)}><ArrowDownToLine size={16}/>Download result</button><button className="ms-text" onClick={job.reset}>Adjust the selection</button></>}><ImageComparison before={file!} after={job.result.blob} name={file!.name}/></MediaLayout>;
 return <MediaLayout title="Select the small area to clean up." busy={job.busy} settings={<><MediaField label="Your selection" detail="Drag a box over the mark. Add several small regions if needed. You can also adjust the pixel coordinates below."><button className="ms-secondary" disabled={!file} onClick={()=>{setRegions(prev=>[...prev,{x:Math.round(dims.w*.4),y:Math.round(dims.h*.4),width:Math.max(1,Math.round(dims.w*.2)),height:Math.max(1,Math.round(dims.h*.2))}]);setActive(regions.length);}}>Add a region</button></MediaField>{regions.length>0&&<><div className="ms-region-list">{regions.map((r,i)=><div key={i}><button type="button" aria-pressed={active===i} onClick={()=>setActive(i)}>Region {i+1}<small>{r.width} × {r.height} px</small></button><button className="ms-icon-button" aria-label={`Remove region ${i+1}`} onClick={()=>{setRegions(prev=>prev.filter((_,j)=>j!==i));setActive(0);}}><X size={14}/></button></div>)}</div>{regions[active]&&<div className="ms-region-fields">{(['x','y','width','height'] as const).map(key=><label key={key}>{key}<input aria-label={`Region ${key}`} type="number" min={key==='x'||key==='y'?0:1} value={regions[active][key]} onChange={e=>update(key,Number(e.target.value))}/></label>)}</div>}</>}<MediaField label="Reconstruction method"><MediaChoices label="Inpainting method" value={method} onChange={setMethod} options={[{value:'telea',label:'Texture',detail:'Fast, thin marks'},{value:'ns',label:'Smooth area',detail:'Larger solid areas'}]}/></MediaField><p className="ms-caption">Keep the total selection under 40% of the image. This reconstructs pixels; it cannot recover the original image behind a mark.</p><MediaRun label="Clean the selected areas" canRun={!!file&&regions.length>0} busy={job.busy} error={job.error} onRun={()=>file&&job.run({endpoint:'/remove-image-watermark',file,params:{regions:JSON.stringify(regions),method},name:buildOutputFilename(file.name,'no_watermark',file.name.split('.').pop()||'png')})}/></>}>
 {file?<><div className="ms-region-stage"><div className="ms-region-canvas"><img src={url} alt={`Select watermark regions on ${file.name}`} onLoad={e=>setDims({w:e.currentTarget.naturalWidth,h:e.currentTarget.naturalHeight})}/><svg viewBox={`0 0 ${dims.w} ${dims.h}`} aria-label="Draw watermark removal regions" style={{touchAction:'none'}} onPointerDown={e=>{if(job.busy)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);origin.current=point(e);setDraft(null);}} onPointerMove={e=>{if(origin.current&&!job.busy)setDraft(draftAt(point(e)));}} onPointerUp={e=>{if(!origin.current)return;const region=draftAt(point(e));origin.current=null;setDraft(null);if(region.width>2&&region.height>2){setRegions(prev=>[...prev,region]);setActive(regions.length);}}} onPointerCancel={()=>{origin.current=null;setDraft(null);}}>{regions.map((r,i)=><rect key={i} {...r} className={i===active?'is-active':''}/>)}{draft&&<rect {...draft} className="is-active"/>}</svg></div></div><p className="ms-caption">{dims.w} × {dims.h} px · {regions.length} selected {regions.length===1?'region':'regions'}</p><MediaUpload compact accepts=".jpg,.jpeg,.png,.webp,.bmp" title="Choose another image" disabled={job.busy} onFiles={files=>resetFile(files[0])}/></>:<MediaUpload accepts=".jpg,.jpeg,.png,.webp,.bmp" title="Bring the image you want to clean." onFiles={files=>resetFile(files[0])}/>}{job.busy&&<><MediaBusy label="Reconstructing the selected pixels"/><button className="ms-text" onClick={job.cancel}>Cancel request</button></>}
 </MediaLayout>;
}
type Metadata={format:string;mode:string;size:[number,number];exif:Record<string,unknown>;info:Record<string,unknown>;gps:Record<string,unknown>};
export function ViewExifUI(){const[file,setFile]=useState<File|null>(null);const[data,setData]=useState<Metadata|null>(null);const[query,setQuery]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const run=async()=>{if(!file||busy)return;setBusy(true);setError('');try{setData(await uploadFileGetJson<Metadata>('/view-exif',file));}catch(e){setError(friendlyError(e instanceof Error?e.message:'Failed','Could not inspect the metadata.'));}finally{setBusy(false);}};const rows=data?(['exif','gps','info'] as const).flatMap(group=>Object.entries(data[group]||{}).map(([name,value])=>({group,name,value:typeof value==='string'?value:JSON.stringify(value)}))).filter(row=>`${row.group} ${row.name} ${row.value}`.toLowerCase().includes(query.toLowerCase())):[];return <MediaLayout title="What else is in your picture?" busy={busy} settings={<><MediaField label="An image can carry more than pixels" detail="Camera details, dates and sometimes location can travel with an image. Inspect what this file contains before sharing it."/><MediaRun label={data?'Inspect again':'Inspect metadata'} canRun={!!file} busy={busy} error={error} onRun={run}/>{data&&<><MediaField label={Object.keys(data.gps||{}).length?'Location data found':'No GPS fields found'} detail={Object.keys(data.gps||{}).length?'This file contains GPS metadata. Review it below before sharing.':'No GPS fields were returned by this metadata reader. Other fields may still identify people or places.'}/><button className="ms-secondary" onClick={()=>downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),buildOutputFilename(file?.name,'metadata','json'))}><ArrowDownToLine size={16}/>Download JSON</button><a className="ms-text" href="/tools/remove-exif">Remove image metadata →</a></>}</>}>
 {file?<><MediaPreview file={file} name={file.name} caption={data?`${data.format} · ${data.mode} · ${data.size.join(' × ')} px`:'Original image'}/><MediaUpload compact accepts=".jpg,.jpeg,.png,.webp,.tif,.tiff,.heic,.heif,.bmp,.gif" title="Choose another image" disabled={busy} onFiles={files=>{setFile(files[0]);setData(null);setQuery('');setError('');}}/></>:<MediaUpload accepts=".jpg,.jpeg,.png,.webp,.tif,.tiff,.heic,.heif,.bmp,.gif" title="Bring your image to inspect." onFiles={files=>setFile(files[0])}/>}{busy&&<MediaBusy label="Reading the image metadata"/>}{data&&<section className="ms-metadata"><header><h3>Inside the file</h3><label><span className="sr-only">Search metadata</span><input type="search" placeholder="Search names or values…" value={query} onChange={e=>setQuery(e.target.value)}/></label></header>{rows.length?<table><thead><tr><th>Field</th><th>Value</th></tr></thead><tbody>{rows.map(row=><tr key={row.group+row.name}><th scope="row"><small>{row.group.toUpperCase()}</small>{row.name}</th><td>{row.value}</td></tr>)}</tbody></table>:<p className="ms-caption">{query?'No metadata matches that search.':'No embedded metadata fields were returned.'}</p>}</section>}
 </MediaLayout>;}
