import { useState } from 'react';
import { ArrowLeft, ArrowRight, X } from 'lucide-react';
import { useToolDefaults } from '@/hooks/useToolDefaults';
import { buildOutputFilename, formatFileSize } from '@/lib/api';
import { ArrangementCanvas } from './media/MediaCanvases';
import { MediaBusy, MediaChoices, MediaField, MediaFinished, MediaLayout, MediaRun, MediaUpload } from './media/MediaStudio';
import { useMediaJob } from './media/useMediaJob';
export function MergeImagesUI(){const[config,,{setField}]=useToolDefaults('merge-images',{direction:'horizontal' as 'horizontal'|'vertical'|'grid'});const{direction}=config;const[files,setFiles]=useState<File[]>([]);const[drag,setDrag]=useState<number|null>(null);const job=useMediaJob();const move=(from:number,to:number)=>{if(job.busy||to<0||to>=files.length)return;setFiles(list=>{const next=[...list];const[item]=next.splice(from,1);next.splice(to,0,item);return next;});};
 if(job.result&&job.status==='done')return <MediaFinished result={job.result} kind="image" title="One picture, made from many." onReset={job.reset}/>;
 return <MediaLayout title="Make a picture with a little more story." busy={job.busy} settings={<><MediaField label="Direction" detail={direction==='horizontal'?'Images line up at the same height.':direction==='vertical'?'Images line up at the same width.':'Images fit in equal cells, using a balanced grid.'}><MediaChoices label="Merge direction" value={direction} onChange={value=>setField('direction',value)} options={[{value:'horizontal',label:'Side by side'},{value:'vertical',label:'Top to bottom'},{value:'grid',label:'A grid'}]}/></MediaField><MediaRun label="Merge images" canRun={files.length>=2} busy={job.busy} error={job.error} onRun={()=>job.run({endpoint:direction==='grid'?'/make-collage':'/merge-images',files,params:direction==='grid'?{columns:Math.ceil(Math.sqrt(files.length))}:{direction},name:buildOutputFilename(files[0]?.name,'merged',direction==='grid'?'jpg':'png')})}/><p className="ms-caption">Add at least two images. Arrange them here before making the final image.</p></>}>
 {files.length>0&&<><ArrangementCanvas files={files} direction={direction} columns={Math.ceil(Math.sqrt(files.length))}/><div className="ms-order-list">{files.map((file,index)=><article key={`${file.name}-${index}`} draggable={!job.busy} onDragStart={()=>setDrag(index)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!=null)move(drag,index);setDrag(null);}}><span className="ms-file-number">{index+1}</span><div><strong>{file.name}</strong><small>{formatFileSize(file.size)}</small></div><button className="ms-icon-button" disabled={job.busy||index===0} aria-label={`Move ${file.name} earlier`} onClick={()=>move(index,index-1)}><ArrowLeft size={14}/></button><button className="ms-icon-button" disabled={job.busy||index===files.length-1} aria-label={`Move ${file.name} later`} onClick={()=>move(index,index+1)}><ArrowRight size={14}/></button><button className="ms-icon-button" disabled={job.busy} aria-label={`Remove ${file.name}`} onClick={()=>setFiles(list=>list.filter((_,i)=>i!==index))}><X size={14}/></button></article>)}</div></>}<MediaUpload accepts=".jpg,.jpeg,.png,.webp,.bmp" multiple disabled={job.busy} compact={files.length>0} title={files.length?'Add more images':'Bring your images together.'} onFiles={next=>setFiles(list=>[...list,...next])}/>{job.busy&&<><MediaBusy label="Joining your images"/><button className="ms-text" onClick={job.cancel}>Cancel request</button></>}
 </MediaLayout>;
}
