import { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { uploadFileGetJson } from '@/lib/api';
import { friendlyError } from '@/lib/utils';
import { emitToolRun } from '@/lib/toolRun';
import { TrimMediaUI } from './TrimMediaUI';
import { MediaSingleTask } from './media/MediaTasks';
import { ImageEditCanvas } from './media/MediaCanvases';
import { MediaBusy, MediaChoices, MediaField, MediaLayout, MediaPreview, MediaRange, MediaRun, MediaUpload } from './media/MediaStudio';
const IMAGE_ACCEPTS='.jpg,.jpeg,.png,.webp,.bmp,.gif,.tif,.tiff';
export function VideoSpeedUI(){const[speed,setSpeed]=useState(1.5);return <MediaSingleTask title="Find a different rhythm." endpoint="/video-speed" accepts=".mp4,.mov,.webm,.avi,.mkv" outputExt="mp4" suffix={`${speed.toFixed(2).replace(/\.00$/,'')}x`} kind="video" params={{speed:speed.toFixed(2)}} options={<><MediaRange label="Playback speed" value={speed} min={.25} max={4} step={.05} unit="×" onChange={setSpeed}/><MediaChoices label="Speed presets" value={speed} onChange={setSpeed} options={[.5,1,1.5,2,4].map(value=>({value,label:`${value}×`}))}/><p className="ms-caption">Play the preview to hear and see this speed. The downloaded video will use the same speed setting.</p></>} preview={file=><MediaPreview file={file} name={file.name} kind="video" playbackRate={speed} caption={`Previewing at ${speed.toFixed(2)}×`}/>}/>;}
export function AudioTrimUI(){return <TrimMediaUI audioOnly/>;}
export function PixelateImageUI(){const[mode,setMode]=useState<'pixelate'|'blur'>('pixelate');const[strength,setStrength]=useState(20);return <MediaSingleTask title="Choose what the picture gives away." endpoint="/pixelate-image" accepts={IMAGE_ACCEPTS} outputExt={file=>/\.jpe?g$/i.test(file.name)?"jpg":"png"} suffix={mode==='pixelate'?'pixelated':'blurred'} params={{mode,strength}} options={<><MediaField label="Effect"><MediaChoices label="Image effect" value={mode} onChange={setMode} options={[{value:'pixelate',label:'Pixelate',detail:'Block mosaic'},{value:'blur',label:'Blur',detail:'Soft focus'}]}/></MediaField><MediaRange label="Strength" value={strength} min={1} max={100} onChange={setStrength}/><p className="ms-caption">This effect covers the entire image. The local preview is approximate; review the processed result before sharing sensitive content.</p></>} preview={file=><ImageEditCanvas file={file} edit={{kind:'pixelate',mode,strength}}/>}/>;}
export function RotateImageUI(){const[degrees,setDegrees]=useState(90);return <MediaSingleTask title="Give your picture a fresh angle." endpoint="/rotate-image" accepts={IMAGE_ACCEPTS} outputExt={file=>/\.(jpe?g|png|webp)$/i.test(file.name)?file.name.split(".").pop()!:"png"} suffix="rotated" params={{degrees}} options={<><MediaField label="Rotation"><MediaChoices label="Rotation angle" value={degrees} onChange={setDegrees} options={[{value:90,label:'90° left'},{value:180,label:'180°'},{value:270,label:'90° right'},{value:0,label:'Original'}]}/></MediaField><MediaRange label="Custom angle" value={degrees} min={-180} max={360} unit="°" onChange={setDegrees} detail="Positive angles rotate counter-clockwise. The canvas expands to keep the whole image."/></>} preview={file=><ImageEditCanvas file={file} edit={{kind:'rotate',degrees}}/>}/>;}
export function FlipImageUI(){const[direction,setDirection]=useState<'horizontal'|'vertical'>('horizontal');return <MediaSingleTask title="See the other side." endpoint="/flip-image" accepts={IMAGE_ACCEPTS} outputExt={file=>/\.(jpe?g|png|webp)$/i.test(file.name)?file.name.split(".").pop()!:"png"} suffix={`flipped-${direction[0]}`} params={{direction}} options={<MediaField label="Mirror direction"><MediaChoices label="Flip direction" value={direction} onChange={setDirection} options={[{value:'horizontal',label:'Left to right',detail:'Horizontal mirror'},{value:'vertical',label:'Top to bottom',detail:'Vertical mirror'}]}/></MediaField>} preview={file=><ImageEditCanvas file={file} edit={{kind:'flip',direction}}/>}/>;}
type PaletteEntry={hex:string;rgb:[number,number,number];percentage:number};
export function ImagePaletteUI(){const[file,setFile]=useState<File|null>(null);const[colors,setColors]=useState(6);const[palette,setPalette]=useState<PaletteEntry[]|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[copied,setCopied]=useState('');
 const run=async()=>{if(!file||busy)return;setBusy(true);setError('');try{const data=await uploadFileGetJson<{palette:PaletteEntry[]}>('/image-palette',file,{colors});setPalette(data.palette);emitToolRun({outcome:'success',files:1});}catch(e){setError(friendlyError(e instanceof Error?e.message:'Failed','Could not extract those colours.'));emitToolRun({outcome:'error',files:1});}finally{setBusy(false);}};
 const copy=async(hex:string)=>{try{await navigator.clipboard.writeText(hex);setCopied(hex);setTimeout(()=>setCopied(''),1500);}catch{setError('Clipboard access is unavailable. Select and copy the colour value below.');}};
 return <MediaLayout title="A palette hiding in plain sight." busy={busy} settings={<><MediaRange label="Number of colours" value={colors} min={2} max={24} onChange={setColors}/><MediaRun label={palette?'Extract a new palette':'Find the colours'} busy={busy} canRun={!!file} onRun={run} error={error}/>{palette&&<button className="ms-secondary" onClick={()=>copy(palette.map(item=>item.hex).join(', '))}><Copy size={14}/>Copy all colours</button>}</>}>
 {file?<><MediaPreview file={file} name={file.name} caption="The source of your palette"/><MediaUpload compact accepts={IMAGE_ACCEPTS} title="Choose another image" disabled={busy} onFiles={files=>{setFile(files[0]);setPalette(null);setError('');}}/></>:<MediaUpload accepts={IMAGE_ACCEPTS} disabled={busy} title="Bring a picture you love." onFiles={files=>setFile(files[0])}/>}
 {busy&&<MediaBusy label="Finding the dominant colours"/>}{palette&&<section className="ms-palette-result"><div className="ms-swatch-row">{palette.map(item=><button key={item.hex} aria-label={`Copy ${item.hex}`} title={`${item.hex} · ${item.percentage.toFixed(1)}%`} style={{background:item.hex,flex:item.percentage||1}} onClick={()=>copy(item.hex)}/>)}</div><div className="ms-palette-values">{palette.map(item=><button key={item.hex} onClick={()=>copy(item.hex)}><span className="ms-palette-dot" style={{background:item.hex}}/><strong>{item.hex} {copied===item.hex&&<Check size={12}/>}</strong><small>RGB {item.rgb.join(', ')} · {item.percentage.toFixed(1)}%</small></button>)}</div><p className="ms-caption" role="status">{copied?'Copied to clipboard.':'Click a colour to copy its hex value.'}</p></section>}
 </MediaLayout>;
}
