import { formatMediaTime, parseMediaTime } from "./media/media-time";
import { useEffect, useState } from 'react';
import { buildOutputFilename } from '@/lib/api';
import { MediaBusy, MediaField, MediaFinished, MediaLayout, MediaPreview, MediaRange, MediaRun, MediaUpload } from './media/MediaStudio';
import { useMediaJob } from './media/useMediaJob';
export function TrimMediaUI({audioOnly=false}:{audioOnly?:boolean}={}){
 const[file,setFile]=useState<File|null>(null);const[start,setStart]=useState('00:00:00');const[end,setEnd]=useState('00:00:10');const[duration,setDuration]=useState(0);const[current,setCurrent]=useState(0);const[seek,setSeek]=useState(0);const job=useMediaJob();const isAudio=audioOnly||!!file&&/\.(mp3|wav|aac|flac|ogg|m4a)$/i.test(file.name);const startSec=parseMediaTime(start),endSec=parseMediaTime(end);const valid=Number.isFinite(startSec)&&Number.isFinite(endSec)&&startSec<endSec&&(!duration||endSec<=duration+.001);const accepts=audioOnly?'.mp3,.wav,.aac,.flac,.ogg,.m4a':'.mp4,.mov,.webm,.avi,.mkv,.mp3,.wav,.aac,.flac,.ogg,.m4a';
 const pick=(files:File[])=>{setFile(files[0]);setDuration(0);setCurrent(0);setStart('00:00:00');setEnd('00:00:10');setSeek(0);job.reset();};
 if(job.result&&job.status==='done')return <MediaFinished result={job.result} kind={isAudio?'audio':'video'} onReset={job.reset} title="Just the part you wanted."/>;
 return <MediaLayout title={isAudio?'Find your favourite few seconds.':'Keep the moment that matters.'} busy={job.busy} settings={<><MediaField label="Your selection"><div className="ms-time-fields"><label>Start (HH:MM:SS)<input aria-label="Start time" value={start} onChange={e=>setStart(e.target.value)} spellCheck={false}/></label><label>End (HH:MM:SS)<input aria-label="End time" value={end} onChange={e=>setEnd(e.target.value)} spellCheck={false}/></label></div><p className="ms-caption">{valid?`${(endSec-startSec).toFixed(2)} seconds will be kept.`:'Choose a valid start before the end, within the clip duration.'}</p></MediaField><MediaRun label={isAudio?'Trim audio':'Trim media'} busy={job.busy} canRun={!!file&&valid} error={job.error} onRun={()=>file&&job.run({endpoint:audioOnly?'/audio-trim':'/trim-media',file,params:{start,end},name:buildOutputFilename(file.name,'trimmed',file.name.split('.').pop()||'mp4')})}/></>}>
 {file?<><MediaPreview file={file} name={file.name} kind={isAudio?'audio':'video'} seek={seek} onTime={setCurrent} onDuration={value=>{setDuration(value);setEnd(formatMediaTime(Math.min(10,value)));}} caption="Play or scrub, then mark the part to keep"/><fieldset disabled={job.busy} className="ms-timeline"><div className="ms-time-row"><strong>{current.toFixed(2)} s</strong><span>{duration?`${duration.toFixed(2)} s total`:'Loading duration…'}</span></div>{duration>0&&<><MediaRange label="Selection starts" value={Number.isFinite(startSec)?startSec:0} min={0} max={duration} step={.01} unit=" s" onChange={value=>{setStart(formatMediaTime(value));setSeek(value);}}/><MediaRange label="Selection ends" value={Number.isFinite(endSec)?Math.min(endSec,duration):duration} min={0} max={duration} step={.01} unit=" s" onChange={value=>{setEnd(formatMediaTime(value));setSeek(value);}}/></>}<div className="ms-actions"><button className="ms-secondary" disabled={job.busy} onClick={()=>setStart(formatMediaTime(current))}>Start at playhead</button><button className="ms-secondary" disabled={job.busy} onClick={()=>setEnd(formatMediaTime(current))}>End at playhead</button>{valid&&<button className="ms-text" disabled={job.busy} onClick={()=>setSeek(startSec)}>Go to selection start</button>}</div></fieldset><MediaUpload compact accepts={accepts} title="Choose a different clip" disabled={job.busy} onFiles={pick}/></>:<MediaUpload accepts={accepts} title={audioOnly?'Bring your audio.':'Bring your video or audio.'} disabled={job.busy} onFiles={pick}/>}
 {job.busy&&<><MediaBusy label="Trimming your selection"/><button className="ms-text" onClick={job.cancel}>Cancel request</button></>}
 </MediaLayout>;
}
