import { useState } from 'react';
import { buildOutputFilename } from '@/lib/api';
import { ConfiguredMediaBatch } from './media/MediaTasks';
import { MediaBusy, MediaChoices, MediaField, MediaFinished, MediaLayout, MediaPreview, MediaRange, MediaRun, MediaUpload } from './media/MediaStudio';
import { useMediaJob } from './media/useMediaJob';
const VIDEO_ACCEPTS='.mp4,.mov,.webm,.avi,.mkv';
export function VideoToPdfUI(){const[frames,setFrames]=useState(12);const[duration,setDuration]=useState(0);return <ConfiguredMediaBatch title="Turn a clip into a contact sheet." endpoint="/video-to-pdf" accepts={VIDEO_ACCEPTS} outputExt="pdf" suffix="frames" resultKind="file" params={{frames}} options={<><MediaRange label="Number of frames" value={frames} min={1} max={60} onChange={setFrames}/><p className="ms-caption">Frames are sampled evenly across the whole video, one per PDF page.{duration>0?` The previewed clip is ${duration.toFixed(1)} seconds long.`:''}</p></>} preview={file=><MediaPreview file={file} name={file.name} kind="video" onDuration={setDuration} caption="Preview the full clip before choosing your frame count"/>}/>;}
export function VideoConverterUI(){const[target,setTarget]=useState('mp4');return <ConfiguredMediaBatch title="Give your video a new format." endpoint="/video-converter" accepts={VIDEO_ACCEPTS+',.m4v'} outputExt={target} suffix="converted" params={{target_format:target}} options={<MediaField label="Save as"><MediaChoices label="Video format" value={target} onChange={setTarget} options={[{value:'mp4',label:'MP4',detail:'H.264 + AAC'},{value:'mov',label:'MOV',detail:'Apple friendly'},{value:'webm',label:'WebM',detail:'VP9 + Opus'},{value:'mkv',label:'MKV',detail:'Flexible container'},{value:'avi',label:'AVI',detail:'Legacy players'}]}/></MediaField>}/>;}
export function VideoResizerUI(){const[preset,setPreset]=useState('720p');return <ConfiguredMediaBatch title="Find the right video size." endpoint="/video-resizer" accepts={VIDEO_ACCEPTS} outputExt="mp4" suffix="resized" params={{preset}} options={<MediaField label="Output resolution" detail="The aspect ratio stays the same. Enlarging a small video cannot add missing detail."><MediaChoices label="Video resolution" value={preset} onChange={setPreset} options={['240p','360p','480p','720p','1080p','1440p'].map(value=>({value,label:value}))}/></MediaField>}/>;}
export function VideoThumbnailUI(){const[time,setTime]=useState(1);const[duration,setDuration]=useState(0);return <ConfiguredMediaBatch title="Pick the frame worth keeping." endpoint="/video-thumbnail" accepts={VIDEO_ACCEPTS} outputExt="jpg" suffix="thumbnail" resultKind="image" params={{time_seconds:time}} options={<><MediaRange label="Frame time" value={time} min={0} max={duration?Math.max(0,duration-.04):60} step={.01} unit=" s" onChange={setTime}/><MediaField label="Exact timestamp"><label className="sr-only" htmlFor="frame-time">Timestamp in seconds</label><input id="frame-time" type="number" min={0} max={duration||86400} step={.01} value={time} onChange={e=>setTime(Math.max(0,Math.min(duration?duration-.04:86400,Number(e.target.value))))}/></MediaField><p className="ms-caption">Drag the time slider to preview the exact moment. For multiple clips, the same timestamp is used for each.</p></>} preview={file=><MediaPreview file={file} name={file.name} kind="video" seek={time} onDuration={value=>{setDuration(value);setTime(t=>Math.min(t,Math.max(0,value-.04)));}} caption={`Frame at ${time.toFixed(2)} seconds`}/>}/>;}
export function GifToMp4UI(){return <ConfiguredMediaBatch title="Turn your loop into a video." endpoint="/gif-to-mp4" accepts=".gif" outputExt="mp4" suffix="animation" kind="image" resultKind="video" options={<MediaField label="A shareable MP4" detail="The animation becomes a silent MP4 video. Preview the original here and play the actual result when it is ready."/>}/>;}
export function AddSubtitlesUI(){const[video,setVideo]=useState<File|null>(null);const[srt,setSrt]=useState<File|null>(null);const[text,setText]=useState('');const job=useMediaJob();if(job.result&&job.status==='done')return <MediaFinished result={job.result} kind="video" onReset={job.reset} title="Your story, with words."/>;return <MediaLayout title="Let every word come through." busy={job.busy} settings={<><MediaField label="Your subtitle file" detail="SRT subtitles are burned into the picture and cannot be switched off."><MediaUpload accepts=".srt" compact disabled={job.busy} title={srt?srt.name:'Choose subtitles (.srt)'} onFiles={files=>{setSrt(files[0]);void files[0].text().then(value=>setText(value.slice(0,12000)));}}/></MediaField><MediaRun label="Add subtitles" canRun={!!video&&!!srt} busy={job.busy} error={job.error} onRun={()=>video&&srt&&job.run({endpoint:'/add-subtitles',file:video,extra:{srt},name:buildOutputFilename(video.name,'subtitled','mp4')})}/></>}>{video?<><MediaPreview file={video} name={video.name} kind="video" caption="Original video · subtitles appear in the finished result"/><MediaUpload compact accepts={VIDEO_ACCEPTS} disabled={job.busy} title="Choose another video" onFiles={files=>setVideo(files[0])}/></>:<MediaUpload accepts={VIDEO_ACCEPTS} disabled={job.busy} title="Bring your video." onFiles={files=>setVideo(files[0])}/>} {srt&&<section className="ms-subtitles-sheet"><h3>Subtitle text</h3><pre>{text}</pre></section>}{job.busy&&<><MediaBusy label="Adding your subtitles"/><button className="ms-text" onClick={job.cancel}>Cancel request</button></>}</MediaLayout>;}
