import { type MediaKind, useMediaUrl, mediaKind } from "./media-files";
import { useEffect, useId, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, FileImage, Film, ImagePlus, Music2, X } from 'lucide-react';
import { downloadBlob, formatFileSize } from '@/lib/api';
import type { FileEntry, UseMultiFileProcessorResult } from '@/hooks/useMultiFileProcessor';
import './media-studio.css';
export function MediaLayout({ title, detail, children, settings, busy = false, className = '' }: { title: string; detail?: ReactNode; children: ReactNode; settings: ReactNode; busy?: boolean; className?: string }) {
  return <div className={`ms-workspace ${className}`} aria-busy={busy}><section className="ms-stage"><header className="ms-stage-heading"><div><span className="ms-kicker">Your workspace</span><h2>{title}</h2></div>{detail && <p>{detail}</p>}</header>{children}</section><aside className="ms-settings"><fieldset disabled={busy}><legend className="ms-kicker">Make it yours</legend>{settings}</fieldset></aside></div>;
}
export function MediaField({ label, detail, children }: { label: string; detail?: ReactNode; children?: ReactNode }) { return <div className="ms-field"><h3>{label}</h3>{children}{detail && <p className="ms-caption">{detail}</p>}</div>; }
export function MediaChoices<T extends string | number>({ label, value, options, onChange }: { label: string; value: T; options: { value: T; label: string; detail?: string }[]; onChange: (value: any) => void }) {
  return <div className="ms-choices" role="group" aria-label={label}>{options.map(option => <button key={option.value} type="button" aria-pressed={value === option.value} onClick={() => onChange(option.value)}><span>{option.label}</span>{option.detail && <small>{option.detail}</small>}{value === option.value && <Check size={13} aria-hidden="true" />}</button>)}</div>;
}
export function MediaRange({ label, value, min, max, step = 1, unit = '', onChange, detail }: { label: string; value: number; min: number; max: number; step?: number; unit?: string; onChange: (value: number) => void; detail?: ReactNode }) {
  const id = useId(); return <div className="ms-field"><label className="ms-range-label" htmlFor={id}>{label}<output htmlFor={id}>{value}{unit}</output></label><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))} />{detail && <p className="ms-caption">{detail}</p>}</div>;
}
export function MediaUpload({ accepts, multiple = false, onFiles, disabled = false, title = 'Bring your image.', detail, compact = false }: { accepts: string; multiple?: boolean; onFiles: (files: File[]) => void; disabled?: boolean; title?: string; detail?: string; compact?: boolean }) {
  const ref = useRef<HTMLInputElement>(null); const [drag, setDrag] = useState(false); const [error, setError] = useState('');
  const add = (input: FileList | File[]) => { if (disabled) return; const files = Array.from(input); const types = accepts.split(',').map(t => t.trim().toLowerCase()); const allowed = files.filter(f => types.some(t => t.startsWith('.') ? f.name.toLowerCase().endsWith(t) : t.endsWith('/*') ? f.type.startsWith(t.slice(0,-1)) : f.type === t)); setError(allowed.length < files.length ? `Choose a supported file: ${accepts}` : ''); if (allowed.length) onFiles(multiple ? allowed : allowed.slice(0,1)); };
  return <div className={`ms-intake-wrap ${compact ? 'ms-intake-compact' : ''}`}><button type="button" className={`ms-intake ${drag ? 'is-dragging' : ''}`} disabled={disabled} onClick={() => ref.current?.click()} onDragOver={e => { e.preventDefault(); if (!disabled) setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); add(e.dataTransfer.files); }}><span className="ms-intake-object"><ImagePlus size={27} strokeWidth={1.5} /></span><strong>{title}</strong><span>{detail || accepts.replace(/\./g,'').toUpperCase().split(',').join(' · ')}</span><small>Choose from your device or drop here</small></button><input ref={ref} type="file" accept={accepts} multiple={multiple} disabled={disabled} aria-label={title} className="sr-only" tabIndex={-1} onChange={e => { if (e.target.files) add(e.target.files); e.target.value = ''; }} />{error && <p className="ms-error" role="alert">{error}</p>}</div>;
}
export function MediaPreview({ file, name, kind, caption = 'Original', style, overlay, playbackRate = 1, muted = false, seek, onDuration, onTime, children }: { file: Blob; name?: string; kind?: MediaKind; caption?: ReactNode; style?: CSSProperties; overlay?: ReactNode; playbackRate?: number; muted?: boolean; seek?: number; onDuration?: (duration: number) => void; onTime?: (time: number) => void; children?: ReactNode }) {
  const url = useMediaUrl(file); const [failed, setFailed] = useState(false); const [dimensions, setDimensions] = useState(''); const ref = useRef<HTMLMediaElement>(null); const actualKind = kind || mediaKind(file, name);
  useEffect(() => { setFailed(false); setDimensions(''); }, [file]);
  useEffect(() => { if (ref.current) ref.current.playbackRate = playbackRate; }, [playbackRate, url]);
  useEffect(() => { if (ref.current && typeof seek === 'number') ref.current.currentTime = Math.max(0, seek); }, [seek]);
  const mediaProps = { src: url, controls: true, muted, preload: 'auto', onError: () => setFailed(true), onLoadedMetadata: (e: React.SyntheticEvent<HTMLMediaElement>) => { const el = e.currentTarget; el.playbackRate = playbackRate; if (typeof seek === 'number') el.currentTime = Math.min(seek, Number.isFinite(el.duration) ? el.duration : seek); if (Number.isFinite(el.duration)) onDuration?.(el.duration); }, onTimeUpdate: (e: React.SyntheticEvent<HTMLMediaElement>) => onTime?.(e.currentTarget.currentTime) };
  return <figure className={`ms-preview ms-preview-${actualKind}`}><div className="ms-preview-surface">{failed || actualKind === 'file' ? <div className="ms-preview-unavailable"><FileImage size={35}/><strong>{name || 'Your file'}</strong><p>{failed ? 'Your browser cannot preview this format. You can still process the original file.' : 'Your file is ready for processing.'}</p></div> : actualKind === 'image' ? <div className="ms-image-wrap"><img src={url} alt={name ? `Preview of ${name}` : 'Image preview'} style={style} onError={() => setFailed(true)} onLoad={e => setDimensions(`${e.currentTarget.naturalWidth} × ${e.currentTarget.naturalHeight} px`)} />{overlay}</div> : actualKind === 'video' ? <video ref={ref as React.RefObject<HTMLVideoElement>} {...mediaProps} playsInline /> : <div className="ms-audio-preview"><Music2 size={42} strokeWidth={1.2}/><strong>{name || 'Your audio'}</strong><audio ref={ref as React.RefObject<HTMLAudioElement>} {...mediaProps}/></div>}{children}</div><figcaption><span>{caption}</span><span>{dimensions || formatFileSize(file.size)}</span></figcaption></figure>;
}
export function ImageComparison({ before, after, name }: { before: Blob; after: Blob; name: string }) {
  const beforeUrl = useMediaUrl(before); const afterUrl = useMediaUrl(after); const [value,setValue] = useState(50); const id=useId();
  return <figure className="ms-comparison"><div className="ms-comparison-images"><img src={afterUrl} alt={`Finished ${name}`} /><img src={beforeUrl} alt={`Original ${name}`} style={{clipPath:`inset(0 ${100-value}% 0 0)`}}/><span className="ms-comparison-divider" style={{left:`${value}%`}}/><span className="ms-before-label">Original</span><span className="ms-after-label">Result</span></div><label htmlFor={id}>Compare the actual result <span>{formatFileSize(before.size)} → {formatFileSize(after.size)}</span></label><input id={id} aria-label="Before and after comparison" type="range" min={0} max={100} value={value} onChange={e=>setValue(Number(e.target.value))}/></figure>;
}
export function MediaBusy({ label = 'Working on your files', done, total, detail }: { label?: string; done?: number; total?: number; detail?: ReactNode }) {
  const actual = total != null && total > 0 && done != null; return <div className="ms-progress" role="status"><div><span className="ms-processing-dot"/><strong>{label}</strong>{actual && <span>{done} / {total}</span>}</div><div className={actual?'ms-progress-track':'ms-progress-track is-indeterminate'} role="progressbar" aria-label={label} aria-valuemin={actual?0:undefined} aria-valuemax={actual?total:undefined} aria-valuenow={actual?done:undefined}><span style={actual?{width:`${(done!/total!)*100}%`}:undefined}/></div><p>{detail || 'Keep this page open. Your original stays unchanged.'}</p></div>;
}
export function MediaBatchStudio({ proc, phase, title, accepts, kind, resultKind, options, action, canProcess = true, onRun, onDownload, onReset, filter, preview, note, details }: { proc: UseMultiFileProcessorResult; phase: 'idle'|'processing'|'done'; title: string; accepts: string; kind: MediaKind; resultKind?: MediaKind; options: ReactNode; action: string; canProcess?: boolean; onRun: (retry?: boolean) => void; onDownload: () => void; onReset: () => void; filter?: (file: File) => boolean; preview?: (file: File) => ReactNode; note?: ReactNode; details?: (entry: FileEntry) => ReactNode }) {
  const [selectedId, setSelectedId] = useState(''); const selected = proc.entries.find(e=>e.id===selectedId) || proc.entries[0]; const busy = phase==='processing'; const finished = phase==='done'; const beforeImages = kind==='image' && selected && !/\.(heic|heif|tiff?)$/i.test(selected.name); const afterKind = resultKind || kind;
  return <MediaLayout title={finished ? proc.doneCount ? `${proc.doneCount} ${proc.doneCount===1?'file is':'files are'} ready.` : 'Let’s try that again.' : title} detail={finished ? proc.doneCount ? 'Review the actual result, then keep what you need.' : 'Your files are still here. Review the message and retry when you’re ready.' : 'A clear preview. A few thoughtful controls.'} busy={busy} settings={<>{!finished ? <>{options}<div className="ms-run"><button className="ms-primary" disabled={!proc.entries.length || !canProcess} onClick={()=>onRun(false)}><ArrowRight size={16}/>{busy?'Processing…':action}</button><p className="ms-caption">{note || 'Your files are uploaded only when you run this tool.'}</p></div></> : <><div className="ms-result-summary"><span className="ms-result-seal">{proc.doneCount ? <Check size={27}/> : <ArrowLeft size={27}/>}</span><h3>{proc.doneCount ? 'Your files, finished.' : 'No result was created.'}</h3><p>{proc.doneCount} ready{proc.failedCount ? ` · ${proc.failedCount} need another try` : ''}</p></div>{proc.doneCount>0 && <button className="ms-primary" onClick={onDownload}><ArrowDownToLine size={16}/>Download {proc.doneCount>1?'all as ZIP':'result'}</button>}{proc.failedCount>0 && <button className="ms-secondary" onClick={()=>onRun(true)}>Retry {proc.failedCount} failed</button>}<button className="ms-text" onClick={onReset}>Start a new set</button></>}</>}>
    {!selected ? <MediaUpload accepts={accepts} multiple disabled={busy} onFiles={files=>proc.addFiles(files,filter)} title={kind==='video'?'Bring your clips.':kind==='audio'?'Bring your sound.':'Bring your images.'} detail={accepts.replace(/\./g,'').toUpperCase().split(',').join(' · ')+' · One or more files'}/> : <><div className="ms-selected-file"><span>{selected.name}</span><span>{formatFileSize(selected.size)}</span></div>{finished && selected.blob ? <>{beforeImages && afterKind==='image' && !/tiff|heic|heif/i.test(selected.blob.type) ? <ImageComparison before={selected.file} after={selected.blob} name={selected.name}/> : <MediaPreview file={selected.blob} name={selected.outName || selected.name} kind={afterKind} caption="Actual result"/>}</> : preview ? preview(selected.file) : <MediaPreview file={selected.file} name={selected.name} kind={kind}/>}<div className="ms-file-shelf" aria-label="Your file queue">{proc.entries.map((entry,i)=><article key={entry.id} className={entry.id===selected.id?'is-selected':''}><button className="ms-file-select" onClick={()=>setSelectedId(entry.id)} aria-pressed={entry.id===selected.id}><span className="ms-file-number">{String(i+1).padStart(2,'0')}</span><span><strong>{entry.name}</strong><small>{entry.status==='queued'?formatFileSize(entry.size):entry.status==='done'?`${formatFileSize(entry.blob?.size || 0)} · Ready`:entry.status==='running'?'Processing…':'Needs another try'}</small>{details?.(entry)}</span></button>{!busy && !finished && <button className="ms-icon-button" onClick={()=>proc.removeFile(entry.id)} aria-label={`Remove ${entry.name}`}><X size={15}/></button>}{entry.error && <p className="ms-error" role="alert">{entry.error}</p>}</article>)}</div>{!finished && <MediaUpload accepts={accepts} multiple compact disabled={busy} title="Add more files" onFiles={files=>proc.addFiles(files,filter)}/>}</>}
    {busy && <MediaBusy done={proc.doneCount+proc.failedCount} total={proc.entries.length}/>}
  </MediaLayout>;
}

export function MediaFinished({result,kind,onReset,title='Ready for your next step.'}:{result:{blob:Blob;name:string};kind?:MediaKind;onReset:()=>void;title?:string}) {return <MediaLayout title={title} detail="Your original stays unchanged." settings={<><div className="ms-result-summary"><span className="ms-result-seal"><Check size={27}/></span><h3>Made it.</h3><p>{formatFileSize(result.blob.size)} · Ready to keep</p></div><button className="ms-primary" onClick={()=>downloadBlob(result.blob,result.name)}><ArrowDownToLine size={16}/>Download again</button><button className="ms-text" onClick={onReset}>Back to the workspace</button></>}><MediaPreview file={result.blob} name={result.name} kind={kind} caption="Actual result"/><p className="ms-caption">{result.name}</p></MediaLayout>;}
export function MediaRun({label,canRun,busy,onRun,onCancel,error}:{label:string;canRun:boolean;busy:boolean;onRun:()=>void;onCancel?:()=>void;error?:string|null}) {useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter'&&canRun&&!busy){event.preventDefault();onRun();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[canRun,busy,onRun]);return <div className="ms-run"><button className="ms-primary" disabled={!canRun||busy} onClick={onRun}><ArrowRight size={16}/>{busy?'Processing…':label}</button>{busy&&onCancel&&<button className="ms-text" onClick={onCancel}>Cancel request</button>}{error&&<p className="ms-error" role="alert">{error}</p>}<p className="ms-caption">Your file is uploaded only when you run this tool.</p></div>;}
