import { useEffect, useRef, useState } from 'react';
import { useMediaUrl } from "./media-files";

type Edit = { kind: 'watermark'; text: string; opacity: number; position: string; fontSize: number } | { kind: 'rotate'; degrees: number } | { kind: 'flip'; direction: 'horizontal'|'vertical' } | { kind: 'pixelate'; mode: 'pixelate'|'blur'; strength: number } | { kind: 'resize'; width: number; height: number; mode: 'resize'|'crop' };
export function ImageEditCanvas({file,edit,caption='Live preview'}:{file:File;edit:Edit;caption?:string}) {
  const url=useMediaUrl(file);const canvas=useRef<HTMLCanvasElement>(null);const [info,setInfo]=useState('');const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false;const image=new Image();image.onload=()=>{if(cancelled||!canvas.current)return;setError('');const sourceW=image.naturalWidth,sourceH=image.naturalHeight;let w=sourceW,h=sourceH;if(edit.kind==='resize'){w=edit.width;h=edit.height;}else if(edit.kind==='rotate'){const rad=edit.degrees*Math.PI/180;w=Math.ceil(Math.abs(sourceW*Math.cos(rad))+Math.abs(sourceH*Math.sin(rad)));h=Math.ceil(Math.abs(sourceW*Math.sin(rad))+Math.abs(sourceH*Math.cos(rad)));}const ratio=Math.min(1,1400/Math.max(w,h));const el=canvas.current;el.width=Math.max(1,Math.round(w*ratio));el.height=Math.max(1,Math.round(h*ratio));const ctx=el.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,el.width,el.height);ctx.save();ctx.scale(ratio,ratio);
    if(edit.kind==='rotate'){ctx.translate(w/2,h/2);ctx.rotate(-edit.degrees*Math.PI/180);ctx.drawImage(image,-sourceW/2,-sourceH/2);}else if(edit.kind==='flip'){ctx.translate(edit.direction==='horizontal'?w:0,edit.direction==='vertical'?h:0);ctx.scale(edit.direction==='horizontal'?-1:1,edit.direction==='vertical'?-1:1);ctx.drawImage(image,0,0);}else if(edit.kind==='resize'){if(edit.mode==='crop'){const srcRatio=sourceW/sourceH,targetRatio=w/h;const cw=srcRatio>targetRatio?sourceH*targetRatio:sourceW;const ch=srcRatio>targetRatio?sourceH:sourceW/targetRatio;ctx.drawImage(image,(sourceW-cw)/2,(sourceH-ch)/2,cw,ch,0,0,w,h);}else ctx.drawImage(image,0,0,w,h);}else if(edit.kind==='pixelate'){if(edit.mode==='blur'){ctx.filter=`blur(${Math.max(1,Math.floor(edit.strength*.4)+1)}px)`;ctx.drawImage(image,0,0);}else{const block=Math.max(2,Math.min(120,Math.floor(edit.strength*.8)+4));const small=document.createElement('canvas');small.width=Math.max(1,Math.floor(w/block));small.height=Math.max(1,Math.floor(h/block));small.getContext('2d')?.drawImage(image,0,0,small.width,small.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,w,h);}}else{ctx.drawImage(image,0,0);ctx.font=`bold ${edit.fontSize}px sans-serif`;ctx.textBaseline='top';ctx.fillStyle=`rgba(128,128,128,${edit.opacity/255})`;const tw=ctx.measureText(edit.text).width,th=edit.fontSize;const x=edit.position.endsWith('left')?20:edit.position.endsWith('right')?w-tw-20:(w-tw)/2;const y=edit.position.startsWith('top')?20:edit.position.startsWith('bottom')?h-th-20:(h-th)/2;if(edit.position==='tile'){for(let yy=0;yy<h;yy+=th+60)for(let xx=0;xx<w;xx+=tw+60)ctx.fillText(edit.text,xx,yy);}else ctx.fillText(edit.text,x,y);}ctx.restore();setInfo(`${w} × ${h} px`);};image.onerror=()=>{if(!cancelled)setError('Your browser cannot preview this image format. The original can still be processed.');};image.src=url;return()=>{cancelled=true;image.onload=null;image.onerror=null;};},[url,edit]);
  return <figure className="ms-preview"><div className="ms-preview-surface"><canvas ref={canvas} aria-label={`${caption} of ${file.name}`} style={{maxWidth:'100%',maxHeight:430,objectFit:'contain'}}/>{error&&<p className="ms-caption">{error}</p>}</div><figcaption><span>{caption}{edit.kind==='watermark'?' · Font appearance may vary':''}</span><span>{info}</span></figcaption></figure>;
}
export function WatermarkCanvas({file,text,position,opacity,fontSize}:{file:File;text:string;position:string;opacity:number;fontSize:number}) {return <ImageEditCanvas file={file} edit={{kind:'watermark',text,position,opacity,fontSize}}/>;}
export function ArrangementCanvas({files,columns=2,spacing=10,bgColor='#ffffff',direction='grid'}:{files:File[];columns?:number;spacing?:number;bgColor?:string;direction?:'horizontal'|'vertical'|'grid'}){
 const ref=useRef<HTMLCanvasElement>(null);const[info,setInfo]=useState('');const[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const urls=files.map(f=>URL.createObjectURL(f));Promise.all(urls.map(url=>new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url;}))).then(images=>{if(cancelled||!images.length||!ref.current)return;setError('');let w=0,h=0;const positions:{x:number;y:number;w:number;h:number}[]=[];if(direction==='grid'){const cw=Math.min(600,Math.floor(images.reduce((a,x)=>a+x.width,0)/images.length));const ch=Math.min(600,Math.floor(images.reduce((a,x)=>a+x.height,0)/images.length));w=columns*cw+(columns+1)*spacing;h=Math.ceil(images.length/columns)*ch+(Math.ceil(images.length/columns)+1)*spacing;images.forEach((im,i)=>{const scale=Math.min(cw/im.width,ch/im.height);const dw=Math.floor(im.width*scale),dh=Math.floor(im.height*scale);positions.push({x:(i%columns)*cw+(i%columns+1)*spacing+(cw-dw)/2,y:Math.floor(i/columns)*ch+(Math.floor(i/columns)+1)*spacing+(ch-dh)/2,w:dw,h:dh});});}else if(direction==='horizontal'){h=Math.max(...images.map(im=>im.height));images.forEach(im=>{const dw=Math.floor(im.width*h/im.height);positions.push({x:w,y:0,w:dw,h});w+=dw;});}else{w=Math.max(...images.map(im=>im.width));images.forEach(im=>{const dh=Math.floor(im.height*w/im.width);positions.push({x:0,y:h,w,h:dh});h+=dh;});}const scale=Math.min(1,1400/Math.max(w,h));const canvas=ref.current;canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const ctx=canvas.getContext('2d');if(!ctx)return;ctx.scale(scale,scale);if(direction==='grid'){ctx.fillStyle=bgColor;ctx.fillRect(0,0,w,h);}images.forEach((im,i)=>{const p=positions[i];ctx.drawImage(im,p.x,p.y,p.w,p.h);});setInfo(`${w} × ${h} px`);}).catch(()=>{if(!cancelled)setError('A preview could not be decoded. Try JPG, PNG or WebP.');});return()=>{cancelled=true;urls.forEach(url=>URL.revokeObjectURL(url));};},[files,columns,spacing,bgColor,direction]);
 return <figure className="ms-preview"><div className="ms-preview-surface"><canvas ref={ref} aria-label="Live image arrangement" style={{maxWidth:'100%',maxHeight:430,objectFit:'contain'}}/>{error&&<p className="ms-error">{error}</p>}</div><figcaption><span>Live arrangement · Drag or use arrows to reorder</span><span>{info}</span></figcaption></figure>;
}
